#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TIAC14")]
public partial class DBTarjetaIndiceDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  partial void InsertTID_PACIENTE(TID_PACIENTE instance);
  partial void UpdateTID_PACIENTE(TID_PACIENTE instance);
  partial void DeleteTID_PACIENTE(TID_PACIENTE instance);
  partial void InsertTID_EXPEDIENTE(TID_EXPEDIENTE instance);
  partial void UpdateTID_EXPEDIENTE(TID_EXPEDIENTE instance);
  partial void DeleteTID_EXPEDIENTE(TID_EXPEDIENTE instance);
  partial void InsertTID_DETALLE_PACIENTE(TID_DETALLE_PACIENTE instance);
  partial void UpdateTID_DETALLE_PACIENTE(TID_DETALLE_PACIENTE instance);
  partial void DeleteTID_DETALLE_PACIENTE(TID_DETALLE_PACIENTE instance);
  partial void InsertTID_TARJETA_INDICE(TID_TARJETA_INDICE instance);
  partial void UpdateTID_TARJETA_INDICE(TID_TARJETA_INDICE instance);
  partial void DeleteTID_TARJETA_INDICE(TID_TARJETA_INDICE instance);
  #endregion
	
	public DBTarjetaIndiceDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TIAC14ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DBTarjetaIndiceDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBTarjetaIndiceDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBTarjetaIndiceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBTarjetaIndiceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<TID_PACIENTE> TID_PACIENTE
	{
		get
		{
			return this.GetTable<TID_PACIENTE>();
		}
	}
	
	public System.Data.Linq.Table<TID_EXPEDIENTE> TID_EXPEDIENTE
	{
		get
		{
			return this.GetTable<TID_EXPEDIENTE>();
		}
	}
	
	public System.Data.Linq.Table<TID_DETALLE_PACIENTE> TID_DETALLE_PACIENTE
	{
		get
		{
			return this.GetTable<TID_DETALLE_PACIENTE>();
		}
	}
	
	public System.Data.Linq.Table<TID_TARJETA_INDICE> TID_TARJETA_INDICE
	{
		get
		{
			return this.GetTable<TID_TARJETA_INDICE>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_INSERTAR_PACIENTE")]
	public int sp_INSERTAR_PACIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TID_IDENTIFICACION", DbType="VarChar(30)")] string tID_IDENTIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUM_IDENTIFICACION", DbType="Int")] System.Nullable<int> nUM_IDENTIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOM_APELLIDO1", DbType="VarChar(30)")] string nOM_APELLIDO1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOM_APELLIDO2", DbType="VarChar(30)")] string nOM_APELLIDO2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOM_NOMBRE", DbType="VarChar(25)")] string nOM_NOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IND_SEXO", DbType="VarChar(15)")] string iND_SEXO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="COD_ESTADO_CIVIL", DbType="VarChar(20)")] string cOD_ESTADO_CIVIL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FEC_NACIMIENTO", DbType="Date")] System.Nullable<System.DateTime> fEC_NACIMIENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACION", DbType="VarChar(100)")] string oBSERVACION)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tID_IDENTIFICACION, nUM_IDENTIFICACION, nOM_APELLIDO1, nOM_APELLIDO2, nOM_NOMBRE, iND_SEXO, cOD_ESTADO_CIVIL, fEC_NACIMIENTO, oBSERVACION);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_INSERT_EXPEDIENTE")]
	public int sp_INSERT_EXPEDIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_PACIENTE", DbType="Int")] System.Nullable<int> cEDULA_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BLOQUE_EXPEDIENTE", DbType="VarChar(20)")] string bLOQUE_EXPEDIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CUBICULO_BLOQUE", DbType="VarChar(20)")] string cUBICULO_BLOQUE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_CREACION_EXPEDIENTE", DbType="Date")] System.Nullable<System.DateTime> fECHA_CREACION_EXPEDIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESTADO_EXPEDIENTE", DbType="VarChar(20)")] string eSTADO_EXPEDIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACION", DbType="VarChar(100)")] string oBSERVACION)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cEDULA_PACIENTE, bLOQUE_EXPEDIENTE, cUBICULO_BLOQUE, fECHA_CREACION_EXPEDIENTE, eSTADO_EXPEDIENTE, oBSERVACION);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_INSERT_DETALLESPACIENTE")]
	public int sp_INSERT_DETALLESPACIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_PADRE", DbType="VarChar(50)")] string nOMBRE_PADRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_MADRE", DbType="VarChar(50)")] string nOMBRE_MADRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOMICILIO", DbType="VarChar(100)")] string dOMICILIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_PACIENTE", DbType="Int")] System.Nullable<int> cEDULA_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_PATRONO", DbType="Int")] System.Nullable<int> cODIGO_PATRONO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_PATRONO", DbType="VarChar(50)")] string nOMBRE_PATRONO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACION", DbType="VarChar(100)")] string oBSERVACION)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE_PADRE, nOMBRE_MADRE, dOMICILIO, cEDULA_PACIENTE, cODIGO_PATRONO, nOMBRE_PATRONO, oBSERVACION);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_INSERTAR_TID")]
	public int sp_INSERTAR_TID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_PACIENTE", DbType="Int")] System.Nullable<int> cEDULA_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_CREACION", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_CREACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESTADO_TARJETA_INDICE", DbType="VarChar(30)")] string eSTADO_TARJETA_INDICE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACION_TARJETA_INDICE", DbType="VarChar(100)")] string oBSERVACION_TARJETA_INDICE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_FUNCIONARIO", DbType="Int")] System.Nullable<int> cEDULA_FUNCIONARIO)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cEDULA_PACIENTE, fECHA_CREACION, eSTADO_TARJETA_INDICE, oBSERVACION_TARJETA_INDICE, cEDULA_FUNCIONARIO);
		return ((int)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TID_PACIENTE")]
public partial class TID_PACIENTE : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _TID_IDENTIFICACION;
	
	private int _NUM_IDENTIFICACION;
	
	private string _NOM_APELLIDO1;
	
	private string _NOM_APELLIDO2;
	
	private string _NOM_NOMBRE;
	
	private string _IND_SEXO;
	
	private string _COD_ESTADO_CIVIL;
	
	private System.Nullable<System.DateTime> _FEC_NACIMIENTO;
	
	private System.Nullable<System.DateTime> _FEC_DEFUNCION;
	
	private string _OBSERVACION;
	
	private EntityRef<TID_DETALLE_PACIENTE> _TID_DETALLE_PACIENTE;
	
	private EntityRef<TID_TARJETA_INDICE> _TID_TARJETA_INDICE;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTID_IDENTIFICACIONChanging(string value);
    partial void OnTID_IDENTIFICACIONChanged();
    partial void OnNUM_IDENTIFICACIONChanging(int value);
    partial void OnNUM_IDENTIFICACIONChanged();
    partial void OnNOM_APELLIDO1Changing(string value);
    partial void OnNOM_APELLIDO1Changed();
    partial void OnNOM_APELLIDO2Changing(string value);
    partial void OnNOM_APELLIDO2Changed();
    partial void OnNOM_NOMBREChanging(string value);
    partial void OnNOM_NOMBREChanged();
    partial void OnIND_SEXOChanging(string value);
    partial void OnIND_SEXOChanged();
    partial void OnCOD_ESTADO_CIVILChanging(string value);
    partial void OnCOD_ESTADO_CIVILChanged();
    partial void OnFEC_NACIMIENTOChanging(System.Nullable<System.DateTime> value);
    partial void OnFEC_NACIMIENTOChanged();
    partial void OnFEC_DEFUNCIONChanging(System.Nullable<System.DateTime> value);
    partial void OnFEC_DEFUNCIONChanged();
    partial void OnOBSERVACIONChanging(string value);
    partial void OnOBSERVACIONChanged();
    #endregion
	
	public TID_PACIENTE()
	{
		this._TID_DETALLE_PACIENTE = default(EntityRef<TID_DETALLE_PACIENTE>);
		this._TID_TARJETA_INDICE = default(EntityRef<TID_TARJETA_INDICE>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TID_IDENTIFICACION", DbType="VarChar(30)")]
	public string TID_IDENTIFICACION
	{
		get
		{
			return this._TID_IDENTIFICACION;
		}
		set
		{
			if ((this._TID_IDENTIFICACION != value))
			{
				this.OnTID_IDENTIFICACIONChanging(value);
				this.SendPropertyChanging();
				this._TID_IDENTIFICACION = value;
				this.SendPropertyChanged("TID_IDENTIFICACION");
				this.OnTID_IDENTIFICACIONChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUM_IDENTIFICACION", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int NUM_IDENTIFICACION
	{
		get
		{
			return this._NUM_IDENTIFICACION;
		}
		set
		{
			if ((this._NUM_IDENTIFICACION != value))
			{
				this.OnNUM_IDENTIFICACIONChanging(value);
				this.SendPropertyChanging();
				this._NUM_IDENTIFICACION = value;
				this.SendPropertyChanged("NUM_IDENTIFICACION");
				this.OnNUM_IDENTIFICACIONChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOM_APELLIDO1", DbType="VarChar(30)")]
	public string NOM_APELLIDO1
	{
		get
		{
			return this._NOM_APELLIDO1;
		}
		set
		{
			if ((this._NOM_APELLIDO1 != value))
			{
				this.OnNOM_APELLIDO1Changing(value);
				this.SendPropertyChanging();
				this._NOM_APELLIDO1 = value;
				this.SendPropertyChanged("NOM_APELLIDO1");
				this.OnNOM_APELLIDO1Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOM_APELLIDO2", DbType="VarChar(30)")]
	public string NOM_APELLIDO2
	{
		get
		{
			return this._NOM_APELLIDO2;
		}
		set
		{
			if ((this._NOM_APELLIDO2 != value))
			{
				this.OnNOM_APELLIDO2Changing(value);
				this.SendPropertyChanging();
				this._NOM_APELLIDO2 = value;
				this.SendPropertyChanged("NOM_APELLIDO2");
				this.OnNOM_APELLIDO2Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOM_NOMBRE", DbType="VarChar(25)")]
	public string NOM_NOMBRE
	{
		get
		{
			return this._NOM_NOMBRE;
		}
		set
		{
			if ((this._NOM_NOMBRE != value))
			{
				this.OnNOM_NOMBREChanging(value);
				this.SendPropertyChanging();
				this._NOM_NOMBRE = value;
				this.SendPropertyChanged("NOM_NOMBRE");
				this.OnNOM_NOMBREChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IND_SEXO", DbType="VarChar(15)")]
	public string IND_SEXO
	{
		get
		{
			return this._IND_SEXO;
		}
		set
		{
			if ((this._IND_SEXO != value))
			{
				this.OnIND_SEXOChanging(value);
				this.SendPropertyChanging();
				this._IND_SEXO = value;
				this.SendPropertyChanged("IND_SEXO");
				this.OnIND_SEXOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD_ESTADO_CIVIL", DbType="VarChar(20)")]
	public string COD_ESTADO_CIVIL
	{
		get
		{
			return this._COD_ESTADO_CIVIL;
		}
		set
		{
			if ((this._COD_ESTADO_CIVIL != value))
			{
				this.OnCOD_ESTADO_CIVILChanging(value);
				this.SendPropertyChanging();
				this._COD_ESTADO_CIVIL = value;
				this.SendPropertyChanged("COD_ESTADO_CIVIL");
				this.OnCOD_ESTADO_CIVILChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FEC_NACIMIENTO", DbType="Date")]
	public System.Nullable<System.DateTime> FEC_NACIMIENTO
	{
		get
		{
			return this._FEC_NACIMIENTO;
		}
		set
		{
			if ((this._FEC_NACIMIENTO != value))
			{
				this.OnFEC_NACIMIENTOChanging(value);
				this.SendPropertyChanging();
				this._FEC_NACIMIENTO = value;
				this.SendPropertyChanged("FEC_NACIMIENTO");
				this.OnFEC_NACIMIENTOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FEC_DEFUNCION", DbType="Date")]
	public System.Nullable<System.DateTime> FEC_DEFUNCION
	{
		get
		{
			return this._FEC_DEFUNCION;
		}
		set
		{
			if ((this._FEC_DEFUNCION != value))
			{
				this.OnFEC_DEFUNCIONChanging(value);
				this.SendPropertyChanging();
				this._FEC_DEFUNCION = value;
				this.SendPropertyChanged("FEC_DEFUNCION");
				this.OnFEC_DEFUNCIONChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACION", DbType="VarChar(100)")]
	public string OBSERVACION
	{
		get
		{
			return this._OBSERVACION;
		}
		set
		{
			if ((this._OBSERVACION != value))
			{
				this.OnOBSERVACIONChanging(value);
				this.SendPropertyChanging();
				this._OBSERVACION = value;
				this.SendPropertyChanged("OBSERVACION");
				this.OnOBSERVACIONChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TID_PACIENTE_TID_DETALLE_PACIENTE", Storage="_TID_DETALLE_PACIENTE", ThisKey="NUM_IDENTIFICACION", OtherKey="CEDULA_PACIENTE", IsUnique=true, IsForeignKey=false)]
	public TID_DETALLE_PACIENTE TID_DETALLE_PACIENTE
	{
		get
		{
			return this._TID_DETALLE_PACIENTE.Entity;
		}
		set
		{
			TID_DETALLE_PACIENTE previousValue = this._TID_DETALLE_PACIENTE.Entity;
			if (((previousValue != value) 
						|| (this._TID_DETALLE_PACIENTE.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._TID_DETALLE_PACIENTE.Entity = null;
					previousValue.TID_PACIENTE = null;
				}
				this._TID_DETALLE_PACIENTE.Entity = value;
				if ((value != null))
				{
					value.TID_PACIENTE = this;
				}
				this.SendPropertyChanged("TID_DETALLE_PACIENTE");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TID_PACIENTE_TID_TARJETA_INDICE", Storage="_TID_TARJETA_INDICE", ThisKey="NUM_IDENTIFICACION", OtherKey="CEDULA_PACIENTE", IsUnique=true, IsForeignKey=false)]
	public TID_TARJETA_INDICE TID_TARJETA_INDICE
	{
		get
		{
			return this._TID_TARJETA_INDICE.Entity;
		}
		set
		{
			TID_TARJETA_INDICE previousValue = this._TID_TARJETA_INDICE.Entity;
			if (((previousValue != value) 
						|| (this._TID_TARJETA_INDICE.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._TID_TARJETA_INDICE.Entity = null;
					previousValue.TID_PACIENTE = null;
				}
				this._TID_TARJETA_INDICE.Entity = value;
				if ((value != null))
				{
					value.TID_PACIENTE = this;
				}
				this.SendPropertyChanged("TID_TARJETA_INDICE");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TID_EXPEDIENTE")]
public partial class TID_EXPEDIENTE : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _CEDULA_PACIENTE;
	
	private string _BLOQUE_EXPEDIENTE;
	
	private string _CUBICULO_BLOQUE;
	
	private System.DateTime _FECHA_CREACION_EXPEDIENTE;
	
	private string _ESTADO_EXPEDIENTE;
	
	private string _OBSERVACION;
	
	private EntityRef<TID_TARJETA_INDICE> _TID_TARJETA_INDICE;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCEDULA_PACIENTEChanging(int value);
    partial void OnCEDULA_PACIENTEChanged();
    partial void OnBLOQUE_EXPEDIENTEChanging(string value);
    partial void OnBLOQUE_EXPEDIENTEChanged();
    partial void OnCUBICULO_BLOQUEChanging(string value);
    partial void OnCUBICULO_BLOQUEChanged();
    partial void OnFECHA_CREACION_EXPEDIENTEChanging(System.DateTime value);
    partial void OnFECHA_CREACION_EXPEDIENTEChanged();
    partial void OnESTADO_EXPEDIENTEChanging(string value);
    partial void OnESTADO_EXPEDIENTEChanged();
    partial void OnOBSERVACIONChanging(string value);
    partial void OnOBSERVACIONChanged();
    #endregion
	
	public TID_EXPEDIENTE()
	{
		this._TID_TARJETA_INDICE = default(EntityRef<TID_TARJETA_INDICE>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_PACIENTE", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int CEDULA_PACIENTE
	{
		get
		{
			return this._CEDULA_PACIENTE;
		}
		set
		{
			if ((this._CEDULA_PACIENTE != value))
			{
				if (this._TID_TARJETA_INDICE.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnCEDULA_PACIENTEChanging(value);
				this.SendPropertyChanging();
				this._CEDULA_PACIENTE = value;
				this.SendPropertyChanged("CEDULA_PACIENTE");
				this.OnCEDULA_PACIENTEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLOQUE_EXPEDIENTE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string BLOQUE_EXPEDIENTE
	{
		get
		{
			return this._BLOQUE_EXPEDIENTE;
		}
		set
		{
			if ((this._BLOQUE_EXPEDIENTE != value))
			{
				this.OnBLOQUE_EXPEDIENTEChanging(value);
				this.SendPropertyChanging();
				this._BLOQUE_EXPEDIENTE = value;
				this.SendPropertyChanged("BLOQUE_EXPEDIENTE");
				this.OnBLOQUE_EXPEDIENTEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUBICULO_BLOQUE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string CUBICULO_BLOQUE
	{
		get
		{
			return this._CUBICULO_BLOQUE;
		}
		set
		{
			if ((this._CUBICULO_BLOQUE != value))
			{
				this.OnCUBICULO_BLOQUEChanging(value);
				this.SendPropertyChanging();
				this._CUBICULO_BLOQUE = value;
				this.SendPropertyChanged("CUBICULO_BLOQUE");
				this.OnCUBICULO_BLOQUEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CREACION_EXPEDIENTE", DbType="Date NOT NULL")]
	public System.DateTime FECHA_CREACION_EXPEDIENTE
	{
		get
		{
			return this._FECHA_CREACION_EXPEDIENTE;
		}
		set
		{
			if ((this._FECHA_CREACION_EXPEDIENTE != value))
			{
				this.OnFECHA_CREACION_EXPEDIENTEChanging(value);
				this.SendPropertyChanging();
				this._FECHA_CREACION_EXPEDIENTE = value;
				this.SendPropertyChanged("FECHA_CREACION_EXPEDIENTE");
				this.OnFECHA_CREACION_EXPEDIENTEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_EXPEDIENTE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string ESTADO_EXPEDIENTE
	{
		get
		{
			return this._ESTADO_EXPEDIENTE;
		}
		set
		{
			if ((this._ESTADO_EXPEDIENTE != value))
			{
				this.OnESTADO_EXPEDIENTEChanging(value);
				this.SendPropertyChanging();
				this._ESTADO_EXPEDIENTE = value;
				this.SendPropertyChanged("ESTADO_EXPEDIENTE");
				this.OnESTADO_EXPEDIENTEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACION", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
	public string OBSERVACION
	{
		get
		{
			return this._OBSERVACION;
		}
		set
		{
			if ((this._OBSERVACION != value))
			{
				this.OnOBSERVACIONChanging(value);
				this.SendPropertyChanging();
				this._OBSERVACION = value;
				this.SendPropertyChanged("OBSERVACION");
				this.OnOBSERVACIONChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TID_TARJETA_INDICE_TID_EXPEDIENTE", Storage="_TID_TARJETA_INDICE", ThisKey="CEDULA_PACIENTE", OtherKey="CEDULA_PACIENTE", IsForeignKey=true)]
	public TID_TARJETA_INDICE TID_TARJETA_INDICE
	{
		get
		{
			return this._TID_TARJETA_INDICE.Entity;
		}
		set
		{
			TID_TARJETA_INDICE previousValue = this._TID_TARJETA_INDICE.Entity;
			if (((previousValue != value) 
						|| (this._TID_TARJETA_INDICE.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._TID_TARJETA_INDICE.Entity = null;
					previousValue.TID_EXPEDIENTE = null;
				}
				this._TID_TARJETA_INDICE.Entity = value;
				if ((value != null))
				{
					value.TID_EXPEDIENTE = this;
					this._CEDULA_PACIENTE = value.CEDULA_PACIENTE;
				}
				else
				{
					this._CEDULA_PACIENTE = default(int);
				}
				this.SendPropertyChanged("TID_TARJETA_INDICE");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TID_DETALLE_PACIENTE")]
public partial class TID_DETALLE_PACIENTE : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _NOMBRE_PADRE;
	
	private string _NOMBRE_MADRE;
	
	private string _DOMICILIO;
	
	private int _CEDULA_PACIENTE;
	
	private int _CODIGO_PATRONO;
	
	private string _NOMBRE_PATRONO;
	
	private string _OBSERVACION;
	
	private EntityRef<TID_PACIENTE> _TID_PACIENTE;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNOMBRE_PADREChanging(string value);
    partial void OnNOMBRE_PADREChanged();
    partial void OnNOMBRE_MADREChanging(string value);
    partial void OnNOMBRE_MADREChanged();
    partial void OnDOMICILIOChanging(string value);
    partial void OnDOMICILIOChanged();
    partial void OnCEDULA_PACIENTEChanging(int value);
    partial void OnCEDULA_PACIENTEChanged();
    partial void OnCODIGO_PATRONOChanging(int value);
    partial void OnCODIGO_PATRONOChanged();
    partial void OnNOMBRE_PATRONOChanging(string value);
    partial void OnNOMBRE_PATRONOChanged();
    partial void OnOBSERVACIONChanging(string value);
    partial void OnOBSERVACIONChanged();
    #endregion
	
	public TID_DETALLE_PACIENTE()
	{
		this._TID_PACIENTE = default(EntityRef<TID_PACIENTE>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PADRE", DbType="VarChar(50)")]
	public string NOMBRE_PADRE
	{
		get
		{
			return this._NOMBRE_PADRE;
		}
		set
		{
			if ((this._NOMBRE_PADRE != value))
			{
				this.OnNOMBRE_PADREChanging(value);
				this.SendPropertyChanging();
				this._NOMBRE_PADRE = value;
				this.SendPropertyChanged("NOMBRE_PADRE");
				this.OnNOMBRE_PADREChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_MADRE", DbType="VarChar(50)")]
	public string NOMBRE_MADRE
	{
		get
		{
			return this._NOMBRE_MADRE;
		}
		set
		{
			if ((this._NOMBRE_MADRE != value))
			{
				this.OnNOMBRE_MADREChanging(value);
				this.SendPropertyChanging();
				this._NOMBRE_MADRE = value;
				this.SendPropertyChanged("NOMBRE_MADRE");
				this.OnNOMBRE_MADREChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMICILIO", DbType="VarChar(100)")]
	public string DOMICILIO
	{
		get
		{
			return this._DOMICILIO;
		}
		set
		{
			if ((this._DOMICILIO != value))
			{
				this.OnDOMICILIOChanging(value);
				this.SendPropertyChanging();
				this._DOMICILIO = value;
				this.SendPropertyChanged("DOMICILIO");
				this.OnDOMICILIOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_PACIENTE", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int CEDULA_PACIENTE
	{
		get
		{
			return this._CEDULA_PACIENTE;
		}
		set
		{
			if ((this._CEDULA_PACIENTE != value))
			{
				if (this._TID_PACIENTE.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnCEDULA_PACIENTEChanging(value);
				this.SendPropertyChanging();
				this._CEDULA_PACIENTE = value;
				this.SendPropertyChanged("CEDULA_PACIENTE");
				this.OnCEDULA_PACIENTEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_PATRONO", DbType="Int NOT NULL")]
	public int CODIGO_PATRONO
	{
		get
		{
			return this._CODIGO_PATRONO;
		}
		set
		{
			if ((this._CODIGO_PATRONO != value))
			{
				this.OnCODIGO_PATRONOChanging(value);
				this.SendPropertyChanging();
				this._CODIGO_PATRONO = value;
				this.SendPropertyChanged("CODIGO_PATRONO");
				this.OnCODIGO_PATRONOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PATRONO", DbType="VarChar(50)")]
	public string NOMBRE_PATRONO
	{
		get
		{
			return this._NOMBRE_PATRONO;
		}
		set
		{
			if ((this._NOMBRE_PATRONO != value))
			{
				this.OnNOMBRE_PATRONOChanging(value);
				this.SendPropertyChanging();
				this._NOMBRE_PATRONO = value;
				this.SendPropertyChanged("NOMBRE_PATRONO");
				this.OnNOMBRE_PATRONOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACION", DbType="VarChar(100)")]
	public string OBSERVACION
	{
		get
		{
			return this._OBSERVACION;
		}
		set
		{
			if ((this._OBSERVACION != value))
			{
				this.OnOBSERVACIONChanging(value);
				this.SendPropertyChanging();
				this._OBSERVACION = value;
				this.SendPropertyChanged("OBSERVACION");
				this.OnOBSERVACIONChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TID_PACIENTE_TID_DETALLE_PACIENTE", Storage="_TID_PACIENTE", ThisKey="CEDULA_PACIENTE", OtherKey="NUM_IDENTIFICACION", IsForeignKey=true)]
	public TID_PACIENTE TID_PACIENTE
	{
		get
		{
			return this._TID_PACIENTE.Entity;
		}
		set
		{
			TID_PACIENTE previousValue = this._TID_PACIENTE.Entity;
			if (((previousValue != value) 
						|| (this._TID_PACIENTE.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._TID_PACIENTE.Entity = null;
					previousValue.TID_DETALLE_PACIENTE = null;
				}
				this._TID_PACIENTE.Entity = value;
				if ((value != null))
				{
					value.TID_DETALLE_PACIENTE = this;
					this._CEDULA_PACIENTE = value.NUM_IDENTIFICACION;
				}
				else
				{
					this._CEDULA_PACIENTE = default(int);
				}
				this.SendPropertyChanged("TID_PACIENTE");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TID_TARJETA_INDICE")]
public partial class TID_TARJETA_INDICE : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _CEDULA_PACIENTE;
	
	private System.Nullable<System.DateTime> _FECHA_CREACION;
	
	private string _ESTADO_TARJETA_INDICE;
	
	private string _OBSERVACION_TARJETA_INDICE;
	
	private System.Nullable<int> _CEDULA_FUNCIONARIO;
	
	private EntityRef<TID_EXPEDIENTE> _TID_EXPEDIENTE;
	
	private EntityRef<TID_PACIENTE> _TID_PACIENTE;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCEDULA_PACIENTEChanging(int value);
    partial void OnCEDULA_PACIENTEChanged();
    partial void OnFECHA_CREACIONChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHA_CREACIONChanged();
    partial void OnESTADO_TARJETA_INDICEChanging(string value);
    partial void OnESTADO_TARJETA_INDICEChanged();
    partial void OnOBSERVACION_TARJETA_INDICEChanging(string value);
    partial void OnOBSERVACION_TARJETA_INDICEChanged();
    partial void OnCEDULA_FUNCIONARIOChanging(System.Nullable<int> value);
    partial void OnCEDULA_FUNCIONARIOChanged();
    #endregion
	
	public TID_TARJETA_INDICE()
	{
		this._TID_EXPEDIENTE = default(EntityRef<TID_EXPEDIENTE>);
		this._TID_PACIENTE = default(EntityRef<TID_PACIENTE>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_PACIENTE", DbType="Int NOT NULL", IsPrimaryKey=true)]
	public int CEDULA_PACIENTE
	{
		get
		{
			return this._CEDULA_PACIENTE;
		}
		set
		{
			if ((this._CEDULA_PACIENTE != value))
			{
				if (this._TID_PACIENTE.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnCEDULA_PACIENTEChanging(value);
				this.SendPropertyChanging();
				this._CEDULA_PACIENTE = value;
				this.SendPropertyChanged("CEDULA_PACIENTE");
				this.OnCEDULA_PACIENTEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CREACION", DbType="DateTime")]
	public System.Nullable<System.DateTime> FECHA_CREACION
	{
		get
		{
			return this._FECHA_CREACION;
		}
		set
		{
			if ((this._FECHA_CREACION != value))
			{
				this.OnFECHA_CREACIONChanging(value);
				this.SendPropertyChanging();
				this._FECHA_CREACION = value;
				this.SendPropertyChanged("FECHA_CREACION");
				this.OnFECHA_CREACIONChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_TARJETA_INDICE", DbType="VarChar(30)")]
	public string ESTADO_TARJETA_INDICE
	{
		get
		{
			return this._ESTADO_TARJETA_INDICE;
		}
		set
		{
			if ((this._ESTADO_TARJETA_INDICE != value))
			{
				this.OnESTADO_TARJETA_INDICEChanging(value);
				this.SendPropertyChanging();
				this._ESTADO_TARJETA_INDICE = value;
				this.SendPropertyChanged("ESTADO_TARJETA_INDICE");
				this.OnESTADO_TARJETA_INDICEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACION_TARJETA_INDICE", DbType="VarChar(100)")]
	public string OBSERVACION_TARJETA_INDICE
	{
		get
		{
			return this._OBSERVACION_TARJETA_INDICE;
		}
		set
		{
			if ((this._OBSERVACION_TARJETA_INDICE != value))
			{
				this.OnOBSERVACION_TARJETA_INDICEChanging(value);
				this.SendPropertyChanging();
				this._OBSERVACION_TARJETA_INDICE = value;
				this.SendPropertyChanged("OBSERVACION_TARJETA_INDICE");
				this.OnOBSERVACION_TARJETA_INDICEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_FUNCIONARIO", DbType="Int")]
	public System.Nullable<int> CEDULA_FUNCIONARIO
	{
		get
		{
			return this._CEDULA_FUNCIONARIO;
		}
		set
		{
			if ((this._CEDULA_FUNCIONARIO != value))
			{
				this.OnCEDULA_FUNCIONARIOChanging(value);
				this.SendPropertyChanging();
				this._CEDULA_FUNCIONARIO = value;
				this.SendPropertyChanged("CEDULA_FUNCIONARIO");
				this.OnCEDULA_FUNCIONARIOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TID_TARJETA_INDICE_TID_EXPEDIENTE", Storage="_TID_EXPEDIENTE", ThisKey="CEDULA_PACIENTE", OtherKey="CEDULA_PACIENTE", IsUnique=true, IsForeignKey=false)]
	public TID_EXPEDIENTE TID_EXPEDIENTE
	{
		get
		{
			return this._TID_EXPEDIENTE.Entity;
		}
		set
		{
			TID_EXPEDIENTE previousValue = this._TID_EXPEDIENTE.Entity;
			if (((previousValue != value) 
						|| (this._TID_EXPEDIENTE.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._TID_EXPEDIENTE.Entity = null;
					previousValue.TID_TARJETA_INDICE = null;
				}
				this._TID_EXPEDIENTE.Entity = value;
				if ((value != null))
				{
					value.TID_TARJETA_INDICE = this;
				}
				this.SendPropertyChanged("TID_EXPEDIENTE");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TID_PACIENTE_TID_TARJETA_INDICE", Storage="_TID_PACIENTE", ThisKey="CEDULA_PACIENTE", OtherKey="NUM_IDENTIFICACION", IsForeignKey=true)]
	public TID_PACIENTE TID_PACIENTE
	{
		get
		{
			return this._TID_PACIENTE.Entity;
		}
		set
		{
			TID_PACIENTE previousValue = this._TID_PACIENTE.Entity;
			if (((previousValue != value) 
						|| (this._TID_PACIENTE.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._TID_PACIENTE.Entity = null;
					previousValue.TID_TARJETA_INDICE = null;
				}
				this._TID_PACIENTE.Entity = value;
				if ((value != null))
				{
					value.TID_TARJETA_INDICE = this;
					this._CEDULA_PACIENTE = value.NUM_IDENTIFICACION;
				}
				else
				{
					this._CEDULA_PACIENTE = default(int);
				}
				this.SendPropertyChanged("TID_PACIENTE");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
