#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TIAC14")]
public partial class DBTarjetaIndiceDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  #endregion
	
	public DBTarjetaIndiceDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TIAC14ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DBTarjetaIndiceDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBTarjetaIndiceDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBTarjetaIndiceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBTarjetaIndiceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_MOVIMIENTO")]
	public int SP_INSERTAR_MOVIMIENTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_PACIENTE", DbType="VarChar(20)")] string cEDULA_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_AREA", DbType="Int")] System.Nullable<int> cODIGO_AREA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_DOCTOR", DbType="Int")] System.Nullable<int> cODIGO_DOCTOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_ULTIMO_REGISTRO", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_ULTIMO_REGISTRO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACION", DbType="VarChar(50)")] string oBSERVACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESTADO_EXPEDIENTE", DbType="NChar(10)")] string eSTADO_EXPEDIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RESPONSABLE", DbType="VarChar(50)")] string rESPONSABLE)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cEDULA_PACIENTE, cODIGO_AREA, cODIGO_DOCTOR, fECHA_ULTIMO_REGISTRO, oBSERVACION, eSTADO_EXPEDIENTE, rESPONSABLE);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_buscar_area")]
	public ISingleResult<sp_buscar_areaResult> sp_buscar_area([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_AREA", DbType="Int")] System.Nullable<int> cODIGO_AREA)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cODIGO_AREA);
		return ((ISingleResult<sp_buscar_areaResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_buscar_doctor")]
	public ISingleResult<sp_buscar_doctorResult> sp_buscar_doctor([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_DOCTOR", DbType="Int")] System.Nullable<int> cODIGO_DOCTOR)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cODIGO_DOCTOR);
		return ((ISingleResult<sp_buscar_doctorResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_INSERTAR_PACIENTE")]
	public int sp_INSERTAR_PACIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUM_IDENTIFICACION", DbType="VarChar(20)")] string nUM_IDENTIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOM_APELLIDO1", DbType="VarChar(30)")] string nOM_APELLIDO1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOM_APELLIDO2", DbType="VarChar(30)")] string nOM_APELLIDO2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOM_NOMBRE", DbType="VarChar(25)")] string nOM_NOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IND_SEXO", DbType="VarChar(15)")] string iND_SEXO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="COD_ESTADO_CIVIL", DbType="VarChar(20)")] string cOD_ESTADO_CIVIL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FEC_NACIMIENTO", DbType="Date")] System.Nullable<System.DateTime> fEC_NACIMIENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACION", DbType="VarChar(100)")] string oBSERVACION)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nUM_IDENTIFICACION, nOM_APELLIDO1, nOM_APELLIDO2, nOM_NOMBRE, iND_SEXO, cOD_ESTADO_CIVIL, fEC_NACIMIENTO, oBSERVACION);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_INSERT_EXPEDIENTE")]
	public int sp_INSERT_EXPEDIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_PACIENTE", DbType="VarChar(20)")] string cEDULA_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BLOQUE_EXPEDIENTE", DbType="VarChar(20)")] string bLOQUE_EXPEDIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CUBICULO_BLOQUE", DbType="VarChar(20)")] string cUBICULO_BLOQUE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_CREACION_EXPEDIENTE", DbType="Date")] System.Nullable<System.DateTime> fECHA_CREACION_EXPEDIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESTADO_EXPEDIENTE", DbType="VarChar(20)")] string eSTADO_EXPEDIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACION", DbType="VarChar(100)")] string oBSERVACION)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cEDULA_PACIENTE, bLOQUE_EXPEDIENTE, cUBICULO_BLOQUE, fECHA_CREACION_EXPEDIENTE, eSTADO_EXPEDIENTE, oBSERVACION);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_INSERT_DETALLESPACIENTE")]
	public int sp_INSERT_DETALLESPACIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_PADRE", DbType="VarChar(50)")] string nOMBRE_PADRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_MADRE", DbType="VarChar(50)")] string nOMBRE_MADRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOMICILIO", DbType="VarChar(100)")] string dOMICILIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_PACIENTE", DbType="VarChar(20)")] string cEDULA_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_PATRONO", DbType="VarChar(50)")] string cODIGO_PATRONO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_PATRONO", DbType="VarChar(50)")] string nOMBRE_PATRONO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACION", DbType="VarChar(100)")] string oBSERVACION)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE_PADRE, nOMBRE_MADRE, dOMICILIO, cEDULA_PACIENTE, cODIGO_PATRONO, nOMBRE_PATRONO, oBSERVACION);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SELECCION_EXISTENCIA_EXPEDIENTE")]
	public ISingleResult<SP_SELECCION_EXISTENCIA_EXPEDIENTEResult> SP_SELECCION_EXISTENCIA_EXPEDIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA", DbType="VarChar(20)")] string cEDULA)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cEDULA);
		return ((ISingleResult<SP_SELECCION_EXISTENCIA_EXPEDIENTEResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_INSERTAR_TID")]
	public int sp_INSERTAR_TID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_PACIENTE", DbType="VarChar(20)")] string cEDULA_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_CREACION", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_CREACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESTADO_TARJETA_INDICE", DbType="VarChar(30)")] string eSTADO_TARJETA_INDICE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACION_TARJETA_INDICE", DbType="VarChar(100)")] string oBSERVACION_TARJETA_INDICE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_FUNCIONARIO", DbType="Int")] System.Nullable<int> cEDULA_FUNCIONARIO)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cEDULA_PACIENTE, fECHA_CREACION, eSTADO_TARJETA_INDICE, oBSERVACION_TARJETA_INDICE, cEDULA_FUNCIONARIO);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_HOJAS_URGENCIA")]
	public int SP_INSERTAR_HOJAS_URGENCIA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_PACIENTE", DbType="VarChar(20)")] string cEDULA_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDO_1_PACIENTE", DbType="VarChar(30)")] string aPELLIDO_1_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDO_2_PACIENTE", DbType="VarChar(30)")] string aPELLIDO_2_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_PACIENTE", DbType="VarChar(25)")] string nOMBRE_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUMERO_ASEGURADO", DbType="VarChar(50)")] string nUMERO_ASEGURADO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_REGISTRO", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_REGISTRO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACION", DbType="VarChar(50)")] string oBSERVACION)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cEDULA_PACIENTE, aPELLIDO_1_PACIENTE, aPELLIDO_2_PACIENTE, nOMBRE_PACIENTE, nUMERO_ASEGURADO, fECHA_REGISTRO, oBSERVACION);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_EXAMENES_EXTERNOS")]
	public int SP_INSERTAR_EXAMENES_EXTERNOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_PACIENTE", DbType="VarChar(20)")] string cEDULA_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDO_1_PACIENTE", DbType="VarChar(30)")] string aPELLIDO_1_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDO_2_PACIENTE", DbType="VarChar(30)")] string aPELLIDO_2_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_PACIENTE", DbType="VarChar(25)")] string nOMBRE_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESPECIALIDAD", DbType="VarChar(50)")] string eSPECIALIDAD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_REGISTRO", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_REGISTRO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACION", DbType="VarChar(100)")] string oBSERVACION)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cEDULA_PACIENTE, aPELLIDO_1_PACIENTE, aPELLIDO_2_PACIENTE, nOMBRE_PACIENTE, eSPECIALIDAD, fECHA_REGISTRO, oBSERVACION);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_BUSCAR_PACIENTE")]
	public ISingleResult<SP_BUSCAR_PACIENTEResult> SP_BUSCAR_PACIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_PACIENTE", DbType="VarChar(25)")] string nOMBRE_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AP1_PACIENTE", DbType="VarChar(30)")] string aP1_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AP2_PACIENTE", DbType="VarChar(30)")] string aP2_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CED_PACIENTE", DbType="VarChar(20)")] string cED_PACIENTE)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE_PACIENTE, aP1_PACIENTE, aP2_PACIENTE, cED_PACIENTE);
		return ((ISingleResult<SP_BUSCAR_PACIENTEResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Selecionar_Paciente")]
	public ISingleResult<sp_Selecionar_PacienteResult> sp_Selecionar_Paciente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="VarChar(20)")] string cedula)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula);
		return ((ISingleResult<sp_Selecionar_PacienteResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SELECCIONAR_EXPEDIENTE")]
	public ISingleResult<SP_SELECCIONAR_EXPEDIENTEResult> SP_SELECCIONAR_EXPEDIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_PACIENTE", DbType="VarChar(20)")] string cEDULA_PACIENTE)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cEDULA_PACIENTE);
		return ((ISingleResult<SP_SELECCIONAR_EXPEDIENTEResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GENERAR_HISTORIAL_MOVIMIENTO")]
	public ISingleResult<GENERAR_HISTORIAL_MOVIMIENTOResult> GENERAR_HISTORIAL_MOVIMIENTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_PACIENTE", DbType="VarChar(20)")] string cEDULA_PACIENTE)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cEDULA_PACIENTE);
		return ((ISingleResult<GENERAR_HISTORIAL_MOVIMIENTOResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_APLICACIONSEGURIDAD")]
	public ISingleResult<SP_APLICACIONSEGURIDADResult> SP_APLICACIONSEGURIDAD([global::System.Data.Linq.Mapping.ParameterAttribute(Name="USUARIO", DbType="VarChar(20)")] string uSUARIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLAVE", DbType="VarChar(20)")] string cLAVE)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), uSUARIO, cLAVE);
		return ((ISingleResult<SP_APLICACIONSEGURIDADResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_MEDICO")]
	public int SP_INSERTAR_MEDICO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIDO_MEDICO", DbType="Int")] System.Nullable<int> cODIDO_MEDICO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDO_1_DOCTOR", DbType="VarChar(25)")] string aPELLIDO_1_DOCTOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_DOCTOR", DbType="VarChar(25)")] string nOMBRE_DOCTOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDO_2_DOCTOR", DbType="VarChar(25)")] string aPELLIDO_2_DOCTOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESPECIALIDAD", DbType="VarChar(25)")] string eSPECIALIDAD, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AREA_DE_TRABAJO", DbType="VarChar(25)")] string aREA_DE_TRABAJO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="EST", DbType="VarChar(20)")] string eST)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cODIDO_MEDICO, aPELLIDO_1_DOCTOR, nOMBRE_DOCTOR, aPELLIDO_2_DOCTOR, eSPECIALIDAD, aREA_DE_TRABAJO, eST);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_BUSCARDOCTOR")]
	public ISingleResult<SP_BUSCARDOCTORResult> SP_BUSCARDOCTOR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_DOCTOR", DbType="Int")] System.Nullable<int> cODIGO_DOCTOR)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cODIGO_DOCTOR);
		return ((ISingleResult<SP_BUSCARDOCTORResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_ELIMINARDOCTOR")]
	public int SP_ELIMINARDOCTOR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO", DbType="Int")] System.Nullable<int> cODIGO)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cODIGO);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_AREA")]
	public int SP_INSERTAR_AREA([global::System.Data.Linq.Mapping.ParameterAttribute(Name="AREA_CODIGO", DbType="Int")] System.Nullable<int> aREA_CODIGO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_DEPARTAMENTO", DbType="VarChar(40)")] string nOMBRE_DEPARTAMENTO)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aREA_CODIGO, nOMBRE_DEPARTAMENTO);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_USUARIO")]
	public int SP_INSERTAR_USUARIO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA", DbType="Int")] System.Nullable<int> cEDULA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDO1", DbType="VarChar(30)")] string aPELLIDO1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="APELLIDO2", DbType="VarChar(30)")] string aPELLIDO2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE", DbType="VarChar(25)")] string nOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="TELEFONO", DbType="Int")] System.Nullable<int> tELEFONO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CARNET", DbType="Int")] System.Nullable<int> cARNET, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DIRECCION", DbType="VarChar(100)")] string dIRECCION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_NACIMIENTO", DbType="Date")] System.Nullable<System.DateTime> fECHA_NACIMIENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="AREA_TRABAJO", DbType="VarChar(40)")] string aREA_TRABAJO)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cEDULA, aPELLIDO1, aPELLIDO2, nOMBRE, tELEFONO, cARNET, dIRECCION, fECHA_NACIMIENTO, aREA_TRABAJO);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SELECCION_USUARIOS")]
	public ISingleResult<SP_SELECCION_USUARIOSResult> SP_SELECCION_USUARIOS([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA", DbType="Int")] System.Nullable<int> cEDULA)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cEDULA);
		return ((ISingleResult<SP_SELECCION_USUARIOSResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_ROLLES")]
	public int SP_INSERTAR_ROLLES([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA", DbType="Int")] System.Nullable<int> cEDULA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ROL", DbType="VarChar(30)")] string rOL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CLAVE", DbType="VarChar(20)")] string cLAVE)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cEDULA, rOL, cLAVE);
		return ((int)(result.ReturnValue));
	}
}

public partial class sp_buscar_areaResult
{
	
	private string _NOMBRE_DEPARTAMENTO;
	
	public sp_buscar_areaResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_DEPARTAMENTO", DbType="VarChar(40)")]
	public string NOMBRE_DEPARTAMENTO
	{
		get
		{
			return this._NOMBRE_DEPARTAMENTO;
		}
		set
		{
			if ((this._NOMBRE_DEPARTAMENTO != value))
			{
				this._NOMBRE_DEPARTAMENTO = value;
			}
		}
	}
}

public partial class sp_buscar_doctorResult
{
	
	private string _NOMBRE_DOCTOR;
	
	private string _APELLIDO_1_DOCTOR;
	
	public sp_buscar_doctorResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_DOCTOR", DbType="NChar(10)")]
	public string NOMBRE_DOCTOR
	{
		get
		{
			return this._NOMBRE_DOCTOR;
		}
		set
		{
			if ((this._NOMBRE_DOCTOR != value))
			{
				this._NOMBRE_DOCTOR = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO_1_DOCTOR", DbType="VarChar(30)")]
	public string APELLIDO_1_DOCTOR
	{
		get
		{
			return this._APELLIDO_1_DOCTOR;
		}
		set
		{
			if ((this._APELLIDO_1_DOCTOR != value))
			{
				this._APELLIDO_1_DOCTOR = value;
			}
		}
	}
}

public partial class SP_SELECCION_EXISTENCIA_EXPEDIENTEResult
{
	
	private string _CEDULA_PACIENTE;
	
	private string _ESTADO_EXPEDIENTE;
	
	public SP_SELECCION_EXISTENCIA_EXPEDIENTEResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_PACIENTE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string CEDULA_PACIENTE
	{
		get
		{
			return this._CEDULA_PACIENTE;
		}
		set
		{
			if ((this._CEDULA_PACIENTE != value))
			{
				this._CEDULA_PACIENTE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_EXPEDIENTE", DbType="NChar(10)")]
	public string ESTADO_EXPEDIENTE
	{
		get
		{
			return this._ESTADO_EXPEDIENTE;
		}
		set
		{
			if ((this._ESTADO_EXPEDIENTE != value))
			{
				this._ESTADO_EXPEDIENTE = value;
			}
		}
	}
}

public partial class SP_BUSCAR_PACIENTEResult
{
	
	private string _Nombre;
	
	private string _Apellido;
	
	private string _SegundoApellido;
	
	private string _Identificaciòn;
	
	private System.Nullable<System.DateTime> _Fecha;
	
	public SP_BUSCAR_PACIENTEResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(25)")]
	public string Nombre
	{
		get
		{
			return this._Nombre;
		}
		set
		{
			if ((this._Nombre != value))
			{
				this._Nombre = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Apellido", DbType="VarChar(30)")]
	public string Apellido
	{
		get
		{
			return this._Apellido;
		}
		set
		{
			if ((this._Apellido != value))
			{
				this._Apellido = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SegundoApellido", DbType="VarChar(30)")]
	public string SegundoApellido
	{
		get
		{
			return this._SegundoApellido;
		}
		set
		{
			if ((this._SegundoApellido != value))
			{
				this._SegundoApellido = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Identificaciòn", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string Identificaciòn
	{
		get
		{
			return this._Identificaciòn;
		}
		set
		{
			if ((this._Identificaciòn != value))
			{
				this._Identificaciòn = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date")]
	public System.Nullable<System.DateTime> Fecha
	{
		get
		{
			return this._Fecha;
		}
		set
		{
			if ((this._Fecha != value))
			{
				this._Fecha = value;
			}
		}
	}
}

public partial class sp_Selecionar_PacienteResult
{
	
	private string _NUM_IDENTIFICACION;
	
	private string _NOM_APELLIDO1;
	
	private string _NOM_APELLIDO2;
	
	private string _NOM_NOMBRE;
	
	private string _IND_SEXO;
	
	private string _COD_ESTADO_CIVIL;
	
	private System.Nullable<System.DateTime> _FEC_NACIMIENTO;
	
	private string _OBSERVACION;
	
	private string _NOMBRE_PADRE;
	
	private string _NOMBRE_MADRE;
	
	private string _DOMICILIO;
	
	private string _CODIGO_PATRONO;
	
	private string _NOMBRE_PATRONO;
	
	private string _OBSERVACION1;
	
	private string _BLOQUE_EXPEDIENTE;
	
	private string _CUBICULO_EXPEDIENTE;
	
	private System.Nullable<System.DateTime> _FECHA_CREACION_EXPEDIENTE;
	
	private string _OBSERVACION2;
	
	private string _ESTADO_EXPEDIENTE;
	
	private string _algo;
	
	public sp_Selecionar_PacienteResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUM_IDENTIFICACION", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string NUM_IDENTIFICACION
	{
		get
		{
			return this._NUM_IDENTIFICACION;
		}
		set
		{
			if ((this._NUM_IDENTIFICACION != value))
			{
				this._NUM_IDENTIFICACION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOM_APELLIDO1", DbType="VarChar(30)")]
	public string NOM_APELLIDO1
	{
		get
		{
			return this._NOM_APELLIDO1;
		}
		set
		{
			if ((this._NOM_APELLIDO1 != value))
			{
				this._NOM_APELLIDO1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOM_APELLIDO2", DbType="VarChar(30)")]
	public string NOM_APELLIDO2
	{
		get
		{
			return this._NOM_APELLIDO2;
		}
		set
		{
			if ((this._NOM_APELLIDO2 != value))
			{
				this._NOM_APELLIDO2 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOM_NOMBRE", DbType="VarChar(25)")]
	public string NOM_NOMBRE
	{
		get
		{
			return this._NOM_NOMBRE;
		}
		set
		{
			if ((this._NOM_NOMBRE != value))
			{
				this._NOM_NOMBRE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IND_SEXO", DbType="VarChar(15)")]
	public string IND_SEXO
	{
		get
		{
			return this._IND_SEXO;
		}
		set
		{
			if ((this._IND_SEXO != value))
			{
				this._IND_SEXO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD_ESTADO_CIVIL", DbType="VarChar(20)")]
	public string COD_ESTADO_CIVIL
	{
		get
		{
			return this._COD_ESTADO_CIVIL;
		}
		set
		{
			if ((this._COD_ESTADO_CIVIL != value))
			{
				this._COD_ESTADO_CIVIL = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FEC_NACIMIENTO", DbType="Date")]
	public System.Nullable<System.DateTime> FEC_NACIMIENTO
	{
		get
		{
			return this._FEC_NACIMIENTO;
		}
		set
		{
			if ((this._FEC_NACIMIENTO != value))
			{
				this._FEC_NACIMIENTO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACION", DbType="VarChar(100)")]
	public string OBSERVACION
	{
		get
		{
			return this._OBSERVACION;
		}
		set
		{
			if ((this._OBSERVACION != value))
			{
				this._OBSERVACION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PADRE", DbType="VarChar(50)")]
	public string NOMBRE_PADRE
	{
		get
		{
			return this._NOMBRE_PADRE;
		}
		set
		{
			if ((this._NOMBRE_PADRE != value))
			{
				this._NOMBRE_PADRE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_MADRE", DbType="VarChar(50)")]
	public string NOMBRE_MADRE
	{
		get
		{
			return this._NOMBRE_MADRE;
		}
		set
		{
			if ((this._NOMBRE_MADRE != value))
			{
				this._NOMBRE_MADRE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMICILIO", DbType="VarChar(100)")]
	public string DOMICILIO
	{
		get
		{
			return this._DOMICILIO;
		}
		set
		{
			if ((this._DOMICILIO != value))
			{
				this._DOMICILIO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_PATRONO", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
	public string CODIGO_PATRONO
	{
		get
		{
			return this._CODIGO_PATRONO;
		}
		set
		{
			if ((this._CODIGO_PATRONO != value))
			{
				this._CODIGO_PATRONO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PATRONO", DbType="VarChar(50)")]
	public string NOMBRE_PATRONO
	{
		get
		{
			return this._NOMBRE_PATRONO;
		}
		set
		{
			if ((this._NOMBRE_PATRONO != value))
			{
				this._NOMBRE_PATRONO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACION1", DbType="VarChar(100)")]
	public string OBSERVACION1
	{
		get
		{
			return this._OBSERVACION1;
		}
		set
		{
			if ((this._OBSERVACION1 != value))
			{
				this._OBSERVACION1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLOQUE_EXPEDIENTE", DbType="VarChar(20)")]
	public string BLOQUE_EXPEDIENTE
	{
		get
		{
			return this._BLOQUE_EXPEDIENTE;
		}
		set
		{
			if ((this._BLOQUE_EXPEDIENTE != value))
			{
				this._BLOQUE_EXPEDIENTE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUBICULO_EXPEDIENTE", DbType="VarChar(20)")]
	public string CUBICULO_EXPEDIENTE
	{
		get
		{
			return this._CUBICULO_EXPEDIENTE;
		}
		set
		{
			if ((this._CUBICULO_EXPEDIENTE != value))
			{
				this._CUBICULO_EXPEDIENTE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CREACION_EXPEDIENTE", DbType="Date")]
	public System.Nullable<System.DateTime> FECHA_CREACION_EXPEDIENTE
	{
		get
		{
			return this._FECHA_CREACION_EXPEDIENTE;
		}
		set
		{
			if ((this._FECHA_CREACION_EXPEDIENTE != value))
			{
				this._FECHA_CREACION_EXPEDIENTE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACION2", DbType="VarChar(50)")]
	public string OBSERVACION2
	{
		get
		{
			return this._OBSERVACION2;
		}
		set
		{
			if ((this._OBSERVACION2 != value))
			{
				this._OBSERVACION2 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_EXPEDIENTE", DbType="NChar(10)")]
	public string ESTADO_EXPEDIENTE
	{
		get
		{
			return this._ESTADO_EXPEDIENTE;
		}
		set
		{
			if ((this._ESTADO_EXPEDIENTE != value))
			{
				this._ESTADO_EXPEDIENTE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_algo", DbType="VarChar(20)")]
	public string algo
	{
		get
		{
			return this._algo;
		}
		set
		{
			if ((this._algo != value))
			{
				this._algo = value;
			}
		}
	}
}

public partial class SP_SELECCIONAR_EXPEDIENTEResult
{
	
	private string _Bloque;
	
	private string _Cubiculo;
	
	private System.Nullable<System.DateTime> _Fecha;
	
	private string _Observacion;
	
	private string _Estado;
	
	public SP_SELECCIONAR_EXPEDIENTEResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bloque", DbType="VarChar(20)")]
	public string Bloque
	{
		get
		{
			return this._Bloque;
		}
		set
		{
			if ((this._Bloque != value))
			{
				this._Bloque = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cubiculo", DbType="VarChar(20)")]
	public string Cubiculo
	{
		get
		{
			return this._Cubiculo;
		}
		set
		{
			if ((this._Cubiculo != value))
			{
				this._Cubiculo = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="Date")]
	public System.Nullable<System.DateTime> Fecha
	{
		get
		{
			return this._Fecha;
		}
		set
		{
			if ((this._Fecha != value))
			{
				this._Fecha = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observacion", DbType="VarChar(50)")]
	public string Observacion
	{
		get
		{
			return this._Observacion;
		}
		set
		{
			if ((this._Observacion != value))
			{
				this._Observacion = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="NChar(10)")]
	public string Estado
	{
		get
		{
			return this._Estado;
		}
		set
		{
			if ((this._Estado != value))
			{
				this._Estado = value;
			}
		}
	}
}

public partial class GENERAR_HISTORIAL_MOVIMIENTOResult
{
	
	private System.Nullable<int> _Área;
	
	private System.Nullable<int> _Doctor;
	
	private System.Nullable<System.DateTime> _Fecha;
	
	private string _Observaciòn;
	
	private string _Estado;
	
	private string _Responsable;
	
	public GENERAR_HISTORIAL_MOVIMIENTOResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Área", DbType="Int")]
	public System.Nullable<int> Área
	{
		get
		{
			return this._Área;
		}
		set
		{
			if ((this._Área != value))
			{
				this._Área = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Doctor", DbType="Int")]
	public System.Nullable<int> Doctor
	{
		get
		{
			return this._Doctor;
		}
		set
		{
			if ((this._Doctor != value))
			{
				this._Doctor = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Fecha", DbType="DateTime")]
	public System.Nullable<System.DateTime> Fecha
	{
		get
		{
			return this._Fecha;
		}
		set
		{
			if ((this._Fecha != value))
			{
				this._Fecha = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Observaciòn", DbType="VarChar(50)")]
	public string Observaciòn
	{
		get
		{
			return this._Observaciòn;
		}
		set
		{
			if ((this._Observaciòn != value))
			{
				this._Observaciòn = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Estado", DbType="NChar(10)")]
	public string Estado
	{
		get
		{
			return this._Estado;
		}
		set
		{
			if ((this._Estado != value))
			{
				this._Estado = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Responsable", DbType="VarChar(50)")]
	public string Responsable
	{
		get
		{
			return this._Responsable;
		}
		set
		{
			if ((this._Responsable != value))
			{
				this._Responsable = value;
			}
		}
	}
}

public partial class SP_APLICACIONSEGURIDADResult
{
	
	private string _EXISTENCIA;
	
	public SP_APLICACIONSEGURIDADResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXISTENCIA", DbType="VarChar(10)")]
	public string EXISTENCIA
	{
		get
		{
			return this._EXISTENCIA;
		}
		set
		{
			if ((this._EXISTENCIA != value))
			{
				this._EXISTENCIA = value;
			}
		}
	}
}

public partial class SP_BUSCARDOCTORResult
{
	
	private string _APELLIDO_1_DOCTOR;
	
	private string _APELLIDO_2_DOCTOR;
	
	private string _NOMBRE_DOCTOR;
	
	private string _ESPECIALIDAD_DOCTOR;
	
	private string _AREA_TRABAJO_DOCTOR;
	
	private string _ESTADO_DOCTOR;
	
	private System.Nullable<int> _ESTADO;
	
	public SP_BUSCARDOCTORResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO_1_DOCTOR", DbType="VarChar(30)")]
	public string APELLIDO_1_DOCTOR
	{
		get
		{
			return this._APELLIDO_1_DOCTOR;
		}
		set
		{
			if ((this._APELLIDO_1_DOCTOR != value))
			{
				this._APELLIDO_1_DOCTOR = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO_2_DOCTOR", DbType="VarChar(30)")]
	public string APELLIDO_2_DOCTOR
	{
		get
		{
			return this._APELLIDO_2_DOCTOR;
		}
		set
		{
			if ((this._APELLIDO_2_DOCTOR != value))
			{
				this._APELLIDO_2_DOCTOR = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_DOCTOR", DbType="NChar(10)")]
	public string NOMBRE_DOCTOR
	{
		get
		{
			return this._NOMBRE_DOCTOR;
		}
		set
		{
			if ((this._NOMBRE_DOCTOR != value))
			{
				this._NOMBRE_DOCTOR = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESPECIALIDAD_DOCTOR", DbType="VarChar(40)")]
	public string ESPECIALIDAD_DOCTOR
	{
		get
		{
			return this._ESPECIALIDAD_DOCTOR;
		}
		set
		{
			if ((this._ESPECIALIDAD_DOCTOR != value))
			{
				this._ESPECIALIDAD_DOCTOR = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA_TRABAJO_DOCTOR", DbType="VarChar(30)")]
	public string AREA_TRABAJO_DOCTOR
	{
		get
		{
			return this._AREA_TRABAJO_DOCTOR;
		}
		set
		{
			if ((this._AREA_TRABAJO_DOCTOR != value))
			{
				this._AREA_TRABAJO_DOCTOR = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_DOCTOR", DbType="VarChar(20)")]
	public string ESTADO_DOCTOR
	{
		get
		{
			return this._ESTADO_DOCTOR;
		}
		set
		{
			if ((this._ESTADO_DOCTOR != value))
			{
				this._ESTADO_DOCTOR = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO", DbType="Int")]
	public System.Nullable<int> ESTADO
	{
		get
		{
			return this._ESTADO;
		}
		set
		{
			if ((this._ESTADO != value))
			{
				this._ESTADO = value;
			}
		}
	}
}

public partial class SP_SELECCION_USUARIOSResult
{
	
	private string _APELLIDO_1_FUNCIONARIO;
	
	private string _APELLIDO_2_FUNCIONARIO;
	
	private string _NOMBRE_FUNCIONARIO;
	
	private System.Nullable<int> _TELEFONO_FUNCIONARIO;
	
	private System.Nullable<int> _CARNET_CCSS_FUNCIONARIO;
	
	private string _DIRECCION_FUNCIONARIO;
	
	private System.Nullable<System.DateTime> _FECHA_NACIMIENTO;
	
	private string _AREA_TRABAJO_FUNCIONARIO;
	
	private string _ESTAD;
	
	public SP_SELECCION_USUARIOSResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO_1_FUNCIONARIO", DbType="VarChar(30)")]
	public string APELLIDO_1_FUNCIONARIO
	{
		get
		{
			return this._APELLIDO_1_FUNCIONARIO;
		}
		set
		{
			if ((this._APELLIDO_1_FUNCIONARIO != value))
			{
				this._APELLIDO_1_FUNCIONARIO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APELLIDO_2_FUNCIONARIO", DbType="VarChar(30)")]
	public string APELLIDO_2_FUNCIONARIO
	{
		get
		{
			return this._APELLIDO_2_FUNCIONARIO;
		}
		set
		{
			if ((this._APELLIDO_2_FUNCIONARIO != value))
			{
				this._APELLIDO_2_FUNCIONARIO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_FUNCIONARIO", DbType="VarChar(25)")]
	public string NOMBRE_FUNCIONARIO
	{
		get
		{
			return this._NOMBRE_FUNCIONARIO;
		}
		set
		{
			if ((this._NOMBRE_FUNCIONARIO != value))
			{
				this._NOMBRE_FUNCIONARIO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TELEFONO_FUNCIONARIO", DbType="Int")]
	public System.Nullable<int> TELEFONO_FUNCIONARIO
	{
		get
		{
			return this._TELEFONO_FUNCIONARIO;
		}
		set
		{
			if ((this._TELEFONO_FUNCIONARIO != value))
			{
				this._TELEFONO_FUNCIONARIO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CARNET_CCSS_FUNCIONARIO", DbType="Int")]
	public System.Nullable<int> CARNET_CCSS_FUNCIONARIO
	{
		get
		{
			return this._CARNET_CCSS_FUNCIONARIO;
		}
		set
		{
			if ((this._CARNET_CCSS_FUNCIONARIO != value))
			{
				this._CARNET_CCSS_FUNCIONARIO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIRECCION_FUNCIONARIO", DbType="VarChar(100)")]
	public string DIRECCION_FUNCIONARIO
	{
		get
		{
			return this._DIRECCION_FUNCIONARIO;
		}
		set
		{
			if ((this._DIRECCION_FUNCIONARIO != value))
			{
				this._DIRECCION_FUNCIONARIO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_NACIMIENTO", DbType="Date")]
	public System.Nullable<System.DateTime> FECHA_NACIMIENTO
	{
		get
		{
			return this._FECHA_NACIMIENTO;
		}
		set
		{
			if ((this._FECHA_NACIMIENTO != value))
			{
				this._FECHA_NACIMIENTO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AREA_TRABAJO_FUNCIONARIO", DbType="VarChar(40)")]
	public string AREA_TRABAJO_FUNCIONARIO
	{
		get
		{
			return this._AREA_TRABAJO_FUNCIONARIO;
		}
		set
		{
			if ((this._AREA_TRABAJO_FUNCIONARIO != value))
			{
				this._AREA_TRABAJO_FUNCIONARIO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTAD", DbType="VarChar(10)")]
	public string ESTAD
	{
		get
		{
			return this._ESTAD;
		}
		set
		{
			if ((this._ESTAD != value))
			{
				this._ESTAD = value;
			}
		}
	}
}
#pragma warning restore 1591
