#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TIAC14")]
public partial class DBTarjetaIndiceDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  partial void InsertTID_TARJETA_INDICE(TID_TARJETA_INDICE instance);
  partial void UpdateTID_TARJETA_INDICE(TID_TARJETA_INDICE instance);
  partial void DeleteTID_TARJETA_INDICE(TID_TARJETA_INDICE instance);
  #endregion
	
	public DBTarjetaIndiceDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TIAC14ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DBTarjetaIndiceDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBTarjetaIndiceDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBTarjetaIndiceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBTarjetaIndiceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<TID_EXPEDIENTES> TID_EXPEDIENTES
	{
		get
		{
			return this.GetTable<TID_EXPEDIENTES>();
		}
	}
	
	public System.Data.Linq.Table<TID_TARJETA_INDICE> TID_TARJETA_INDICE
	{
		get
		{
			return this.GetTable<TID_TARJETA_INDICE>();
		}
	}
	
	public System.Data.Linq.Table<TID_MOVIMIENTO_EXPEDIENTE> TID_MOVIMIENTO_EXPEDIENTE
	{
		get
		{
			return this.GetTable<TID_MOVIMIENTO_EXPEDIENTE>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_INSERTAR_PACIENTE")]
	public int sp_INSERTAR_PACIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TID_IDENTIFICACION", DbType="VarChar(30)")] string tID_IDENTIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUM_IDENTIFICACION", DbType="Int")] System.Nullable<int> nUM_IDENTIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOM_APELLIDO1", DbType="VarChar(30)")] string nOM_APELLIDO1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOM_APELLIDO2", DbType="VarChar(30)")] string nOM_APELLIDO2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOM_NOMBRE", DbType="VarChar(25)")] string nOM_NOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IND_SEXO", DbType="VarChar(15)")] string iND_SEXO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="COD_ESTADO_CIVIL", DbType="VarChar(20)")] string cOD_ESTADO_CIVIL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FEC_NACIMIENTO", DbType="Date")] System.Nullable<System.DateTime> fEC_NACIMIENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACION", DbType="VarChar(100)")] string oBSERVACION)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tID_IDENTIFICACION, nUM_IDENTIFICACION, nOM_APELLIDO1, nOM_APELLIDO2, nOM_NOMBRE, iND_SEXO, cOD_ESTADO_CIVIL, fEC_NACIMIENTO, oBSERVACION);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_INSERT_EXPEDIENTE")]
	public int sp_INSERT_EXPEDIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_PACIENTE", DbType="Int")] System.Nullable<int> cEDULA_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BLOQUE_EXPEDIENTE", DbType="VarChar(20)")] string bLOQUE_EXPEDIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CUBICULO_BLOQUE", DbType="VarChar(20)")] string cUBICULO_BLOQUE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_CREACION_EXPEDIENTE", DbType="Date")] System.Nullable<System.DateTime> fECHA_CREACION_EXPEDIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESTADO_EXPEDIENTE", DbType="VarChar(20)")] string eSTADO_EXPEDIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACION", DbType="VarChar(100)")] string oBSERVACION)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cEDULA_PACIENTE, bLOQUE_EXPEDIENTE, cUBICULO_BLOQUE, fECHA_CREACION_EXPEDIENTE, eSTADO_EXPEDIENTE, oBSERVACION);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_INSERT_DETALLESPACIENTE")]
	public int sp_INSERT_DETALLESPACIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_PADRE", DbType="VarChar(50)")] string nOMBRE_PADRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_MADRE", DbType="VarChar(50)")] string nOMBRE_MADRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOMICILIO", DbType="VarChar(100)")] string dOMICILIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_PACIENTE", DbType="Int")] System.Nullable<int> cEDULA_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_PATRONO", DbType="Int")] System.Nullable<int> cODIGO_PATRONO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_PATRONO", DbType="VarChar(50)")] string nOMBRE_PATRONO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACION", DbType="VarChar(100)")] string oBSERVACION)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE_PADRE, nOMBRE_MADRE, dOMICILIO, cEDULA_PACIENTE, cODIGO_PATRONO, nOMBRE_PATRONO, oBSERVACION);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_INSERTAR_TID")]
	public int sp_INSERTAR_TID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_PACIENTE", DbType="Int")] System.Nullable<int> cEDULA_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_CREACION", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_CREACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESTADO_TARJETA_INDICE", DbType="VarChar(30)")] string eSTADO_TARJETA_INDICE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACION_TARJETA_INDICE", DbType="VarChar(100)")] string oBSERVACION_TARJETA_INDICE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_FUNCIONARIO", DbType="Int")] System.Nullable<int> cEDULA_FUNCIONARIO)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cEDULA_PACIENTE, fECHA_CREACION, eSTADO_TARJETA_INDICE, oBSERVACION_TARJETA_INDICE, cEDULA_FUNCIONARIO);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Selecionar_Paciente")]
	public ISingleResult<sp_Selecionar_PacienteResult> sp_Selecionar_Paciente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="Int")] System.Nullable<int> cedula)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula);
		return ((ISingleResult<sp_Selecionar_PacienteResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_SELECCION_EXISTENCIA_EXPEDIENTE")]
	public ISingleResult<SP_SELECCION_EXISTENCIA_EXPEDIENTEResult> SP_SELECCION_EXISTENCIA_EXPEDIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA", DbType="VarChar(20)")] string cEDULA)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cEDULA);
		return ((ISingleResult<SP_SELECCION_EXISTENCIA_EXPEDIENTEResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR_MOVIMIENTO")]
	public int SP_INSERTAR_MOVIMIENTO([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_PACIENTE", DbType="VarChar(20)")] string cEDULA_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_AREA", DbType="Int")] System.Nullable<int> cODIGO_AREA, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_DOCTOR", DbType="Int")] System.Nullable<int> cODIGO_DOCTOR, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_ULTIMO_REGISTRO", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_ULTIMO_REGISTRO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACION", DbType="VarChar(50)")] string oBSERVACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESTADO_EXPEDIENTE", DbType="NChar(10)")] string eSTADO_EXPEDIENTE)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cEDULA_PACIENTE, cODIGO_AREA, cODIGO_DOCTOR, fECHA_ULTIMO_REGISTRO, oBSERVACION, eSTADO_EXPEDIENTE);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GENERAR_HISTORIAL")]
	public ISingleResult<GENERAR_HISTORIALResult> GENERAR_HISTORIAL([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_PACIENTE", DbType="VarChar(20)")] string cEDULA_PACIENTE)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cEDULA_PACIENTE);
		return ((ISingleResult<GENERAR_HISTORIALResult>)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TID_EXPEDIENTES")]
public partial class TID_EXPEDIENTES
{
	
	private string _CEDULA_PACIENTE;
	
	private string _BLOQUE_EXPEDIENTE;
	
	private string _CUBICULO_EXPEDIENTE;
	
	private System.Nullable<System.DateTime> _FECHA_CREACION_EXPEDIENTE;
	
	private string _OBSERVACION;
	
	private string _ESTADO_EXPEDIENTE;
	
	public TID_EXPEDIENTES()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_PACIENTE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string CEDULA_PACIENTE
	{
		get
		{
			return this._CEDULA_PACIENTE;
		}
		set
		{
			if ((this._CEDULA_PACIENTE != value))
			{
				this._CEDULA_PACIENTE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_BLOQUE_EXPEDIENTE", DbType="VarChar(20)")]
	public string BLOQUE_EXPEDIENTE
	{
		get
		{
			return this._BLOQUE_EXPEDIENTE;
		}
		set
		{
			if ((this._BLOQUE_EXPEDIENTE != value))
			{
				this._BLOQUE_EXPEDIENTE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUBICULO_EXPEDIENTE", DbType="VarChar(20)")]
	public string CUBICULO_EXPEDIENTE
	{
		get
		{
			return this._CUBICULO_EXPEDIENTE;
		}
		set
		{
			if ((this._CUBICULO_EXPEDIENTE != value))
			{
				this._CUBICULO_EXPEDIENTE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CREACION_EXPEDIENTE", DbType="Date")]
	public System.Nullable<System.DateTime> FECHA_CREACION_EXPEDIENTE
	{
		get
		{
			return this._FECHA_CREACION_EXPEDIENTE;
		}
		set
		{
			if ((this._FECHA_CREACION_EXPEDIENTE != value))
			{
				this._FECHA_CREACION_EXPEDIENTE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACION", DbType="VarChar(50)")]
	public string OBSERVACION
	{
		get
		{
			return this._OBSERVACION;
		}
		set
		{
			if ((this._OBSERVACION != value))
			{
				this._OBSERVACION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_EXPEDIENTE", DbType="NChar(10)")]
	public string ESTADO_EXPEDIENTE
	{
		get
		{
			return this._ESTADO_EXPEDIENTE;
		}
		set
		{
			if ((this._ESTADO_EXPEDIENTE != value))
			{
				this._ESTADO_EXPEDIENTE = value;
			}
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TID_TARJETA_INDICE")]
public partial class TID_TARJETA_INDICE : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _CEDULA_PACIENTE;
	
	private System.Nullable<System.DateTime> _FECHA_CREACION;
	
	private string _ESTADO_TARJETA_INDICE;
	
	private string _OBSERVACION_TARJETA_INDICE;
	
	private System.Nullable<int> _CEDULA_FUNCIONARIO;
	
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCEDULA_PACIENTEChanging(string value);
    partial void OnCEDULA_PACIENTEChanged();
    partial void OnFECHA_CREACIONChanging(System.Nullable<System.DateTime> value);
    partial void OnFECHA_CREACIONChanged();
    partial void OnESTADO_TARJETA_INDICEChanging(string value);
    partial void OnESTADO_TARJETA_INDICEChanged();
    partial void OnOBSERVACION_TARJETA_INDICEChanging(string value);
    partial void OnOBSERVACION_TARJETA_INDICEChanged();
    partial void OnCEDULA_FUNCIONARIOChanging(System.Nullable<int> value);
    partial void OnCEDULA_FUNCIONARIOChanged();
    #endregion
	
	public TID_TARJETA_INDICE()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_PACIENTE", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string CEDULA_PACIENTE
	{
		get
		{
			return this._CEDULA_PACIENTE;
		}
		set
		{
			if ((this._CEDULA_PACIENTE != value))
			{
				this.OnCEDULA_PACIENTEChanging(value);
				this.SendPropertyChanging();
				this._CEDULA_PACIENTE = value;
				this.SendPropertyChanged("CEDULA_PACIENTE");
				this.OnCEDULA_PACIENTEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_CREACION", DbType="DateTime")]
	public System.Nullable<System.DateTime> FECHA_CREACION
	{
		get
		{
			return this._FECHA_CREACION;
		}
		set
		{
			if ((this._FECHA_CREACION != value))
			{
				this.OnFECHA_CREACIONChanging(value);
				this.SendPropertyChanging();
				this._FECHA_CREACION = value;
				this.SendPropertyChanged("FECHA_CREACION");
				this.OnFECHA_CREACIONChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_TARJETA_INDICE", DbType="VarChar(30)")]
	public string ESTADO_TARJETA_INDICE
	{
		get
		{
			return this._ESTADO_TARJETA_INDICE;
		}
		set
		{
			if ((this._ESTADO_TARJETA_INDICE != value))
			{
				this.OnESTADO_TARJETA_INDICEChanging(value);
				this.SendPropertyChanging();
				this._ESTADO_TARJETA_INDICE = value;
				this.SendPropertyChanged("ESTADO_TARJETA_INDICE");
				this.OnESTADO_TARJETA_INDICEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACION_TARJETA_INDICE", DbType="VarChar(100)")]
	public string OBSERVACION_TARJETA_INDICE
	{
		get
		{
			return this._OBSERVACION_TARJETA_INDICE;
		}
		set
		{
			if ((this._OBSERVACION_TARJETA_INDICE != value))
			{
				this.OnOBSERVACION_TARJETA_INDICEChanging(value);
				this.SendPropertyChanging();
				this._OBSERVACION_TARJETA_INDICE = value;
				this.SendPropertyChanged("OBSERVACION_TARJETA_INDICE");
				this.OnOBSERVACION_TARJETA_INDICEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_FUNCIONARIO", DbType="Int")]
	public System.Nullable<int> CEDULA_FUNCIONARIO
	{
		get
		{
			return this._CEDULA_FUNCIONARIO;
		}
		set
		{
			if ((this._CEDULA_FUNCIONARIO != value))
			{
				this.OnCEDULA_FUNCIONARIOChanging(value);
				this.SendPropertyChanging();
				this._CEDULA_FUNCIONARIO = value;
				this.SendPropertyChanged("CEDULA_FUNCIONARIO");
				this.OnCEDULA_FUNCIONARIOChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TID_MOVIMIENTO_EXPEDIENTE")]
public partial class TID_MOVIMIENTO_EXPEDIENTE
{
	
	private string _CEDULA_PACIENTE;
	
	private System.Nullable<int> _CODIGO_AREA;
	
	private System.Nullable<int> _CODIGO_DOCTOR;
	
	private System.Nullable<System.DateTime> _FECHA_ULTIMO_REGISTRO;
	
	private string _OBSERVACION_MOVIMIENTO;
	
	private string _ESTADO_EXPEDIENTE;
	
	public TID_MOVIMIENTO_EXPEDIENTE()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_PACIENTE", DbType="VarChar(20)")]
	public string CEDULA_PACIENTE
	{
		get
		{
			return this._CEDULA_PACIENTE;
		}
		set
		{
			if ((this._CEDULA_PACIENTE != value))
			{
				this._CEDULA_PACIENTE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_AREA", DbType="Int")]
	public System.Nullable<int> CODIGO_AREA
	{
		get
		{
			return this._CODIGO_AREA;
		}
		set
		{
			if ((this._CODIGO_AREA != value))
			{
				this._CODIGO_AREA = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_DOCTOR", DbType="Int")]
	public System.Nullable<int> CODIGO_DOCTOR
	{
		get
		{
			return this._CODIGO_DOCTOR;
		}
		set
		{
			if ((this._CODIGO_DOCTOR != value))
			{
				this._CODIGO_DOCTOR = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ULTIMO_REGISTRO", DbType="DateTime")]
	public System.Nullable<System.DateTime> FECHA_ULTIMO_REGISTRO
	{
		get
		{
			return this._FECHA_ULTIMO_REGISTRO;
		}
		set
		{
			if ((this._FECHA_ULTIMO_REGISTRO != value))
			{
				this._FECHA_ULTIMO_REGISTRO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACION_MOVIMIENTO", DbType="VarChar(50)")]
	public string OBSERVACION_MOVIMIENTO
	{
		get
		{
			return this._OBSERVACION_MOVIMIENTO;
		}
		set
		{
			if ((this._OBSERVACION_MOVIMIENTO != value))
			{
				this._OBSERVACION_MOVIMIENTO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_EXPEDIENTE", DbType="NChar(10)")]
	public string ESTADO_EXPEDIENTE
	{
		get
		{
			return this._ESTADO_EXPEDIENTE;
		}
		set
		{
			if ((this._ESTADO_EXPEDIENTE != value))
			{
				this._ESTADO_EXPEDIENTE = value;
			}
		}
	}
}

public partial class sp_Selecionar_PacienteResult
{
	
	private int _NUM_IDENTIFICACION;
	
	private string _NOM_APELLIDO1;
	
	private string _NOM_APELLIDO2;
	
	private string _NOM_NOMBRE;
	
	private string _IND_SEXO;
	
	private string _COD_ESTADO_CIVIL;
	
	private System.Nullable<System.DateTime> _FEC_NACIMIENTO;
	
	private string _OBSERVACION;
	
	private string _NOMBRE_PADRE;
	
	private string _NOMBRE_MADRE;
	
	private string _DOMICILIO;
	
	private int _CODIGO_PATRONO;
	
	private string _NOMBRE_PATRONO;
	
	private string _OBSERVACION1;
	
	public sp_Selecionar_PacienteResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUM_IDENTIFICACION", DbType="Int NOT NULL")]
	public int NUM_IDENTIFICACION
	{
		get
		{
			return this._NUM_IDENTIFICACION;
		}
		set
		{
			if ((this._NUM_IDENTIFICACION != value))
			{
				this._NUM_IDENTIFICACION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOM_APELLIDO1", DbType="VarChar(30)")]
	public string NOM_APELLIDO1
	{
		get
		{
			return this._NOM_APELLIDO1;
		}
		set
		{
			if ((this._NOM_APELLIDO1 != value))
			{
				this._NOM_APELLIDO1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOM_APELLIDO2", DbType="VarChar(30)")]
	public string NOM_APELLIDO2
	{
		get
		{
			return this._NOM_APELLIDO2;
		}
		set
		{
			if ((this._NOM_APELLIDO2 != value))
			{
				this._NOM_APELLIDO2 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOM_NOMBRE", DbType="VarChar(25)")]
	public string NOM_NOMBRE
	{
		get
		{
			return this._NOM_NOMBRE;
		}
		set
		{
			if ((this._NOM_NOMBRE != value))
			{
				this._NOM_NOMBRE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IND_SEXO", DbType="VarChar(15)")]
	public string IND_SEXO
	{
		get
		{
			return this._IND_SEXO;
		}
		set
		{
			if ((this._IND_SEXO != value))
			{
				this._IND_SEXO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD_ESTADO_CIVIL", DbType="VarChar(20)")]
	public string COD_ESTADO_CIVIL
	{
		get
		{
			return this._COD_ESTADO_CIVIL;
		}
		set
		{
			if ((this._COD_ESTADO_CIVIL != value))
			{
				this._COD_ESTADO_CIVIL = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FEC_NACIMIENTO", DbType="Date")]
	public System.Nullable<System.DateTime> FEC_NACIMIENTO
	{
		get
		{
			return this._FEC_NACIMIENTO;
		}
		set
		{
			if ((this._FEC_NACIMIENTO != value))
			{
				this._FEC_NACIMIENTO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACION", DbType="VarChar(100)")]
	public string OBSERVACION
	{
		get
		{
			return this._OBSERVACION;
		}
		set
		{
			if ((this._OBSERVACION != value))
			{
				this._OBSERVACION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PADRE", DbType="VarChar(50)")]
	public string NOMBRE_PADRE
	{
		get
		{
			return this._NOMBRE_PADRE;
		}
		set
		{
			if ((this._NOMBRE_PADRE != value))
			{
				this._NOMBRE_PADRE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_MADRE", DbType="VarChar(50)")]
	public string NOMBRE_MADRE
	{
		get
		{
			return this._NOMBRE_MADRE;
		}
		set
		{
			if ((this._NOMBRE_MADRE != value))
			{
				this._NOMBRE_MADRE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMICILIO", DbType="VarChar(100)")]
	public string DOMICILIO
	{
		get
		{
			return this._DOMICILIO;
		}
		set
		{
			if ((this._DOMICILIO != value))
			{
				this._DOMICILIO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_PATRONO", DbType="Int NOT NULL")]
	public int CODIGO_PATRONO
	{
		get
		{
			return this._CODIGO_PATRONO;
		}
		set
		{
			if ((this._CODIGO_PATRONO != value))
			{
				this._CODIGO_PATRONO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PATRONO", DbType="VarChar(50)")]
	public string NOMBRE_PATRONO
	{
		get
		{
			return this._NOMBRE_PATRONO;
		}
		set
		{
			if ((this._NOMBRE_PATRONO != value))
			{
				this._NOMBRE_PATRONO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACION1", DbType="VarChar(100)")]
	public string OBSERVACION1
	{
		get
		{
			return this._OBSERVACION1;
		}
		set
		{
			if ((this._OBSERVACION1 != value))
			{
				this._OBSERVACION1 = value;
			}
		}
	}
}

public partial class SP_SELECCION_EXISTENCIA_EXPEDIENTEResult
{
	
	private string _CEDULA_PACIENTE;
	
	private string _ESTADO_EXPEDIENTE;
	
	public SP_SELECCION_EXISTENCIA_EXPEDIENTEResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CEDULA_PACIENTE", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
	public string CEDULA_PACIENTE
	{
		get
		{
			return this._CEDULA_PACIENTE;
		}
		set
		{
			if ((this._CEDULA_PACIENTE != value))
			{
				this._CEDULA_PACIENTE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_EXPEDIENTE", DbType="NChar(10)")]
	public string ESTADO_EXPEDIENTE
	{
		get
		{
			return this._ESTADO_EXPEDIENTE;
		}
		set
		{
			if ((this._ESTADO_EXPEDIENTE != value))
			{
				this._ESTADO_EXPEDIENTE = value;
			}
		}
	}
}

public partial class GENERAR_HISTORIALResult
{
	
	private System.Nullable<int> _CODIGO_AREA;
	
	private System.Nullable<int> _CODIGO_DOCTOR;
	
	private System.Nullable<System.DateTime> _FECHA_ULTIMO_REGISTRO;
	
	private string _OBSERVACION_MOVIMIENTO;
	
	private string _ESTADO_EXPEDIENTE;
	
	private string _RESPONSABLE;
	
	public GENERAR_HISTORIALResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_AREA", DbType="Int")]
	public System.Nullable<int> CODIGO_AREA
	{
		get
		{
			return this._CODIGO_AREA;
		}
		set
		{
			if ((this._CODIGO_AREA != value))
			{
				this._CODIGO_AREA = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_DOCTOR", DbType="Int")]
	public System.Nullable<int> CODIGO_DOCTOR
	{
		get
		{
			return this._CODIGO_DOCTOR;
		}
		set
		{
			if ((this._CODIGO_DOCTOR != value))
			{
				this._CODIGO_DOCTOR = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FECHA_ULTIMO_REGISTRO", DbType="DateTime")]
	public System.Nullable<System.DateTime> FECHA_ULTIMO_REGISTRO
	{
		get
		{
			return this._FECHA_ULTIMO_REGISTRO;
		}
		set
		{
			if ((this._FECHA_ULTIMO_REGISTRO != value))
			{
				this._FECHA_ULTIMO_REGISTRO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACION_MOVIMIENTO", DbType="VarChar(50)")]
	public string OBSERVACION_MOVIMIENTO
	{
		get
		{
			return this._OBSERVACION_MOVIMIENTO;
		}
		set
		{
			if ((this._OBSERVACION_MOVIMIENTO != value))
			{
				this._OBSERVACION_MOVIMIENTO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ESTADO_EXPEDIENTE", DbType="NChar(10)")]
	public string ESTADO_EXPEDIENTE
	{
		get
		{
			return this._ESTADO_EXPEDIENTE;
		}
		set
		{
			if ((this._ESTADO_EXPEDIENTE != value))
			{
				this._ESTADO_EXPEDIENTE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESPONSABLE", DbType="VarChar(50)")]
	public string RESPONSABLE
	{
		get
		{
			return this._RESPONSABLE;
		}
		set
		{
			if ((this._RESPONSABLE != value))
			{
				this._RESPONSABLE = value;
			}
		}
	}
}
#pragma warning restore 1591
