#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.34014
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TIAC14")]
public partial class DBTarjetaIndiceDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Definiciones de métodos de extensibilidad
  partial void OnCreated();
  #endregion
	
	public DBTarjetaIndiceDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TIAC14ConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DBTarjetaIndiceDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBTarjetaIndiceDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBTarjetaIndiceDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DBTarjetaIndiceDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_INSERTAR_PACIENTE")]
	public int sp_INSERTAR_PACIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="TID_IDENTIFICACION", DbType="VarChar(30)")] string tID_IDENTIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NUM_IDENTIFICACION", DbType="Int")] System.Nullable<int> nUM_IDENTIFICACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOM_APELLIDO1", DbType="VarChar(30)")] string nOM_APELLIDO1, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOM_APELLIDO2", DbType="VarChar(30)")] string nOM_APELLIDO2, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOM_NOMBRE", DbType="VarChar(25)")] string nOM_NOMBRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="IND_SEXO", DbType="VarChar(15)")] string iND_SEXO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="COD_ESTADO_CIVIL", DbType="VarChar(20)")] string cOD_ESTADO_CIVIL, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FEC_NACIMIENTO", DbType="Date")] System.Nullable<System.DateTime> fEC_NACIMIENTO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACION", DbType="VarChar(100)")] string oBSERVACION)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tID_IDENTIFICACION, nUM_IDENTIFICACION, nOM_APELLIDO1, nOM_APELLIDO2, nOM_NOMBRE, iND_SEXO, cOD_ESTADO_CIVIL, fEC_NACIMIENTO, oBSERVACION);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_INSERT_EXPEDIENTE")]
	public int sp_INSERT_EXPEDIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_PACIENTE", DbType="Int")] System.Nullable<int> cEDULA_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="BLOQUE_EXPEDIENTE", DbType="VarChar(20)")] string bLOQUE_EXPEDIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CUBICULO_BLOQUE", DbType="VarChar(20)")] string cUBICULO_BLOQUE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_CREACION_EXPEDIENTE", DbType="Date")] System.Nullable<System.DateTime> fECHA_CREACION_EXPEDIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESTADO_EXPEDIENTE", DbType="VarChar(20)")] string eSTADO_EXPEDIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACION", DbType="VarChar(100)")] string oBSERVACION)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cEDULA_PACIENTE, bLOQUE_EXPEDIENTE, cUBICULO_BLOQUE, fECHA_CREACION_EXPEDIENTE, eSTADO_EXPEDIENTE, oBSERVACION);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_INSERT_DETALLESPACIENTE")]
	public int sp_INSERT_DETALLESPACIENTE([global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_PADRE", DbType="VarChar(50)")] string nOMBRE_PADRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_MADRE", DbType="VarChar(50)")] string nOMBRE_MADRE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="DOMICILIO", DbType="VarChar(100)")] string dOMICILIO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_PACIENTE", DbType="Int")] System.Nullable<int> cEDULA_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CODIGO_PATRONO", DbType="Int")] System.Nullable<int> cODIGO_PATRONO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="NOMBRE_PATRONO", DbType="VarChar(50)")] string nOMBRE_PATRONO, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACION", DbType="VarChar(100)")] string oBSERVACION)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nOMBRE_PADRE, nOMBRE_MADRE, dOMICILIO, cEDULA_PACIENTE, cODIGO_PATRONO, nOMBRE_PATRONO, oBSERVACION);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_INSERTAR_TID")]
	public int sp_INSERTAR_TID([global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_PACIENTE", DbType="Int")] System.Nullable<int> cEDULA_PACIENTE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="FECHA_CREACION", DbType="DateTime")] System.Nullable<System.DateTime> fECHA_CREACION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="ESTADO_TARJETA_INDICE", DbType="VarChar(30)")] string eSTADO_TARJETA_INDICE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="OBSERVACION_TARJETA_INDICE", DbType="VarChar(100)")] string oBSERVACION_TARJETA_INDICE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CEDULA_FUNCIONARIO", DbType="Int")] System.Nullable<int> cEDULA_FUNCIONARIO)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cEDULA_PACIENTE, fECHA_CREACION, eSTADO_TARJETA_INDICE, oBSERVACION_TARJETA_INDICE, cEDULA_FUNCIONARIO);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_Selecionar_Paciente")]
	public ISingleResult<sp_Selecionar_PacienteResult> sp_Selecionar_Paciente([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="Int")] System.Nullable<int> cedula)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula);
		return ((ISingleResult<sp_Selecionar_PacienteResult>)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_INSERTAR")]
	public ISingleResult<SP_INSERTARResult> SP_INSERTAR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cedula", DbType="Int")] System.Nullable<int> cedula)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), cedula);
		return ((ISingleResult<SP_INSERTARResult>)(result.ReturnValue));
	}
}

public partial class sp_Selecionar_PacienteResult
{
	
	private int _NUM_IDENTIFICACION;
	
	private string _NOM_APELLIDO1;
	
	private string _NOM_APELLIDO2;
	
	private string _NOM_NOMBRE;
	
	private string _IND_SEXO;
	
	private string _COD_ESTADO_CIVIL;
	
	private System.Nullable<System.DateTime> _FEC_NACIMIENTO;
	
	private string _OBSERVACION;
	
	private string _NOMBRE_PADRE;
	
	private string _NOMBRE_MADRE;
	
	private string _DOMICILIO;
	
	private int _CODIGO_PATRONO;
	
	private string _NOMBRE_PATRONO;
	
	private string _OBSERVACION1;
	
	public sp_Selecionar_PacienteResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUM_IDENTIFICACION", DbType="Int NOT NULL")]
	public int NUM_IDENTIFICACION
	{
		get
		{
			return this._NUM_IDENTIFICACION;
		}
		set
		{
			if ((this._NUM_IDENTIFICACION != value))
			{
				this._NUM_IDENTIFICACION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOM_APELLIDO1", DbType="VarChar(30)")]
	public string NOM_APELLIDO1
	{
		get
		{
			return this._NOM_APELLIDO1;
		}
		set
		{
			if ((this._NOM_APELLIDO1 != value))
			{
				this._NOM_APELLIDO1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOM_APELLIDO2", DbType="VarChar(30)")]
	public string NOM_APELLIDO2
	{
		get
		{
			return this._NOM_APELLIDO2;
		}
		set
		{
			if ((this._NOM_APELLIDO2 != value))
			{
				this._NOM_APELLIDO2 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOM_NOMBRE", DbType="VarChar(25)")]
	public string NOM_NOMBRE
	{
		get
		{
			return this._NOM_NOMBRE;
		}
		set
		{
			if ((this._NOM_NOMBRE != value))
			{
				this._NOM_NOMBRE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IND_SEXO", DbType="VarChar(15)")]
	public string IND_SEXO
	{
		get
		{
			return this._IND_SEXO;
		}
		set
		{
			if ((this._IND_SEXO != value))
			{
				this._IND_SEXO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD_ESTADO_CIVIL", DbType="VarChar(20)")]
	public string COD_ESTADO_CIVIL
	{
		get
		{
			return this._COD_ESTADO_CIVIL;
		}
		set
		{
			if ((this._COD_ESTADO_CIVIL != value))
			{
				this._COD_ESTADO_CIVIL = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FEC_NACIMIENTO", DbType="Date")]
	public System.Nullable<System.DateTime> FEC_NACIMIENTO
	{
		get
		{
			return this._FEC_NACIMIENTO;
		}
		set
		{
			if ((this._FEC_NACIMIENTO != value))
			{
				this._FEC_NACIMIENTO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACION", DbType="VarChar(100)")]
	public string OBSERVACION
	{
		get
		{
			return this._OBSERVACION;
		}
		set
		{
			if ((this._OBSERVACION != value))
			{
				this._OBSERVACION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PADRE", DbType="VarChar(50)")]
	public string NOMBRE_PADRE
	{
		get
		{
			return this._NOMBRE_PADRE;
		}
		set
		{
			if ((this._NOMBRE_PADRE != value))
			{
				this._NOMBRE_PADRE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_MADRE", DbType="VarChar(50)")]
	public string NOMBRE_MADRE
	{
		get
		{
			return this._NOMBRE_MADRE;
		}
		set
		{
			if ((this._NOMBRE_MADRE != value))
			{
				this._NOMBRE_MADRE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMICILIO", DbType="VarChar(100)")]
	public string DOMICILIO
	{
		get
		{
			return this._DOMICILIO;
		}
		set
		{
			if ((this._DOMICILIO != value))
			{
				this._DOMICILIO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_PATRONO", DbType="Int NOT NULL")]
	public int CODIGO_PATRONO
	{
		get
		{
			return this._CODIGO_PATRONO;
		}
		set
		{
			if ((this._CODIGO_PATRONO != value))
			{
				this._CODIGO_PATRONO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PATRONO", DbType="VarChar(50)")]
	public string NOMBRE_PATRONO
	{
		get
		{
			return this._NOMBRE_PATRONO;
		}
		set
		{
			if ((this._NOMBRE_PATRONO != value))
			{
				this._NOMBRE_PATRONO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACION1", DbType="VarChar(100)")]
	public string OBSERVACION1
	{
		get
		{
			return this._OBSERVACION1;
		}
		set
		{
			if ((this._OBSERVACION1 != value))
			{
				this._OBSERVACION1 = value;
			}
		}
	}
}

public partial class SP_INSERTARResult
{
	
	private int _NUM_IDENTIFICACION;
	
	private string _NOM_APELLIDO1;
	
	private string _NOM_APELLIDO2;
	
	private string _NOM_NOMBRE;
	
	private string _IND_SEXO;
	
	private string _COD_ESTADO_CIVIL;
	
	private System.Nullable<System.DateTime> _FEC_NACIMIENTO;
	
	private string _OBSERVACION;
	
	private string _NOMBRE_PADRE;
	
	private string _NOMBRE_MADRE;
	
	private string _DOMICILIO;
	
	private int _CODIGO_PATRONO;
	
	private string _NOMBRE_PATRONO;
	
	private string _OBSERVACION1;
	
	public SP_INSERTARResult()
	{
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NUM_IDENTIFICACION", DbType="Int NOT NULL")]
	public int NUM_IDENTIFICACION
	{
		get
		{
			return this._NUM_IDENTIFICACION;
		}
		set
		{
			if ((this._NUM_IDENTIFICACION != value))
			{
				this._NUM_IDENTIFICACION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOM_APELLIDO1", DbType="VarChar(30)")]
	public string NOM_APELLIDO1
	{
		get
		{
			return this._NOM_APELLIDO1;
		}
		set
		{
			if ((this._NOM_APELLIDO1 != value))
			{
				this._NOM_APELLIDO1 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOM_APELLIDO2", DbType="VarChar(30)")]
	public string NOM_APELLIDO2
	{
		get
		{
			return this._NOM_APELLIDO2;
		}
		set
		{
			if ((this._NOM_APELLIDO2 != value))
			{
				this._NOM_APELLIDO2 = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOM_NOMBRE", DbType="VarChar(25)")]
	public string NOM_NOMBRE
	{
		get
		{
			return this._NOM_NOMBRE;
		}
		set
		{
			if ((this._NOM_NOMBRE != value))
			{
				this._NOM_NOMBRE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IND_SEXO", DbType="VarChar(15)")]
	public string IND_SEXO
	{
		get
		{
			return this._IND_SEXO;
		}
		set
		{
			if ((this._IND_SEXO != value))
			{
				this._IND_SEXO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COD_ESTADO_CIVIL", DbType="VarChar(20)")]
	public string COD_ESTADO_CIVIL
	{
		get
		{
			return this._COD_ESTADO_CIVIL;
		}
		set
		{
			if ((this._COD_ESTADO_CIVIL != value))
			{
				this._COD_ESTADO_CIVIL = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FEC_NACIMIENTO", DbType="Date")]
	public System.Nullable<System.DateTime> FEC_NACIMIENTO
	{
		get
		{
			return this._FEC_NACIMIENTO;
		}
		set
		{
			if ((this._FEC_NACIMIENTO != value))
			{
				this._FEC_NACIMIENTO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACION", DbType="VarChar(100)")]
	public string OBSERVACION
	{
		get
		{
			return this._OBSERVACION;
		}
		set
		{
			if ((this._OBSERVACION != value))
			{
				this._OBSERVACION = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PADRE", DbType="VarChar(50)")]
	public string NOMBRE_PADRE
	{
		get
		{
			return this._NOMBRE_PADRE;
		}
		set
		{
			if ((this._NOMBRE_PADRE != value))
			{
				this._NOMBRE_PADRE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_MADRE", DbType="VarChar(50)")]
	public string NOMBRE_MADRE
	{
		get
		{
			return this._NOMBRE_MADRE;
		}
		set
		{
			if ((this._NOMBRE_MADRE != value))
			{
				this._NOMBRE_MADRE = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DOMICILIO", DbType="VarChar(100)")]
	public string DOMICILIO
	{
		get
		{
			return this._DOMICILIO;
		}
		set
		{
			if ((this._DOMICILIO != value))
			{
				this._DOMICILIO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODIGO_PATRONO", DbType="Int NOT NULL")]
	public int CODIGO_PATRONO
	{
		get
		{
			return this._CODIGO_PATRONO;
		}
		set
		{
			if ((this._CODIGO_PATRONO != value))
			{
				this._CODIGO_PATRONO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOMBRE_PATRONO", DbType="VarChar(50)")]
	public string NOMBRE_PATRONO
	{
		get
		{
			return this._NOMBRE_PATRONO;
		}
		set
		{
			if ((this._NOMBRE_PATRONO != value))
			{
				this._NOMBRE_PATRONO = value;
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OBSERVACION1", DbType="VarChar(100)")]
	public string OBSERVACION1
	{
		get
		{
			return this._OBSERVACION1;
		}
		set
		{
			if ((this._OBSERVACION1 != value))
			{
				this._OBSERVACION1 = value;
			}
		}
	}
}
#pragma warning restore 1591
