<?xml version="1.0" encoding="utf-8"?><Database Name="TIAC14" Class="DBTarjetaIndiceDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=WIN-EDIIQI6V5R4\SQLEXPRESS;Initial Catalog=TIAC14;Persist Security Info=True;User ID=Lester94" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TIAC14ConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.SP_INSERTAR_MOVIMIENTO" Method="SP_INSERTAR_MOVIMIENTO">
    <Parameter Name="CEDULA_PACIENTE" Parameter="cEDULA_PACIENTE" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CODIGO_AREA" Parameter="cODIGO_AREA" Type="System.Int32" DbType="Int" />
    <Parameter Name="CODIGO_DOCTOR" Parameter="cODIGO_DOCTOR" Type="System.Int32" DbType="Int" />
    <Parameter Name="FECHA_ULTIMO_REGISTRO" Parameter="fECHA_ULTIMO_REGISTRO" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="OBSERVACION" Parameter="oBSERVACION" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="ESTADO_EXPEDIENTE" Parameter="eSTADO_EXPEDIENTE" Type="System.String" DbType="NChar(10)" />
    <Parameter Name="RESPONSABLE" Parameter="rESPONSABLE" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_buscar_area" Method="sp_buscar_area">
    <Parameter Name="CODIGO_AREA" Parameter="cODIGO_AREA" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_buscar_areaResult">
      <Column Name="NOMBRE_DEPARTAMENTO" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_buscar_doctor" Method="sp_buscar_doctor">
    <Parameter Name="CODIGO_DOCTOR" Parameter="cODIGO_DOCTOR" Type="System.Int32" DbType="Int" />
    <ElementType Name="sp_buscar_doctorResult">
      <Column Name="NOMBRE_DOCTOR" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="APELLIDO_1_DOCTOR" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_INSERTAR_PACIENTE" Method="sp_INSERTAR_PACIENTE">
    <Parameter Name="NUM_IDENTIFICACION" Parameter="nUM_IDENTIFICACION" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="NOM_APELLIDO1" Parameter="nOM_APELLIDO1" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="NOM_APELLIDO2" Parameter="nOM_APELLIDO2" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="NOM_NOMBRE" Parameter="nOM_NOMBRE" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="IND_SEXO" Parameter="iND_SEXO" Type="System.String" DbType="VarChar(15)" />
    <Parameter Name="COD_ESTADO_CIVIL" Parameter="cOD_ESTADO_CIVIL" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="FEC_NACIMIENTO" Parameter="fEC_NACIMIENTO" Type="System.DateTime" DbType="Date" />
    <Parameter Name="OBSERVACION" Parameter="oBSERVACION" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_INSERT_EXPEDIENTE" Method="sp_INSERT_EXPEDIENTE">
    <Parameter Name="CEDULA_PACIENTE" Parameter="cEDULA_PACIENTE" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="BLOQUE_EXPEDIENTE" Parameter="bLOQUE_EXPEDIENTE" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CUBICULO_BLOQUE" Parameter="cUBICULO_BLOQUE" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="FECHA_CREACION_EXPEDIENTE" Parameter="fECHA_CREACION_EXPEDIENTE" Type="System.DateTime" DbType="Date" />
    <Parameter Name="ESTADO_EXPEDIENTE" Parameter="eSTADO_EXPEDIENTE" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="OBSERVACION" Parameter="oBSERVACION" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.sp_INSERT_DETALLESPACIENTE" Method="sp_INSERT_DETALLESPACIENTE">
    <Parameter Name="NOMBRE_PADRE" Parameter="nOMBRE_PADRE" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NOMBRE_MADRE" Parameter="nOMBRE_MADRE" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="DOMICILIO" Parameter="dOMICILIO" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CEDULA_PACIENTE" Parameter="cEDULA_PACIENTE" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CODIGO_PATRONO" Parameter="cODIGO_PATRONO" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="NOMBRE_PATRONO" Parameter="nOMBRE_PATRONO" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="OBSERVACION" Parameter="oBSERVACION" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SELECCION_EXISTENCIA_EXPEDIENTE" Method="SP_SELECCION_EXISTENCIA_EXPEDIENTE">
    <Parameter Name="CEDULA" Parameter="cEDULA" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="SP_SELECCION_EXISTENCIA_EXPEDIENTEResult">
      <Column Name="CEDULA_PACIENTE" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="ESTADO_EXPEDIENTE" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_INSERTAR_TID" Method="sp_INSERTAR_TID">
    <Parameter Name="CEDULA_PACIENTE" Parameter="cEDULA_PACIENTE" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="FECHA_CREACION" Parameter="fECHA_CREACION" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="ESTADO_TARJETA_INDICE" Parameter="eSTADO_TARJETA_INDICE" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="OBSERVACION_TARJETA_INDICE" Parameter="oBSERVACION_TARJETA_INDICE" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="CEDULA_FUNCIONARIO" Parameter="cEDULA_FUNCIONARIO" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_INSERTAR_HOJAS_URGENCIA" Method="SP_INSERTAR_HOJAS_URGENCIA">
    <Parameter Name="CEDULA_PACIENTE" Parameter="cEDULA_PACIENTE" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="APELLIDO_1_PACIENTE" Parameter="aPELLIDO_1_PACIENTE" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="APELLIDO_2_PACIENTE" Parameter="aPELLIDO_2_PACIENTE" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="NOMBRE_PACIENTE" Parameter="nOMBRE_PACIENTE" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="NUMERO_ASEGURADO" Parameter="nUMERO_ASEGURADO" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="FECHA_REGISTRO" Parameter="fECHA_REGISTRO" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="OBSERVACION" Parameter="oBSERVACION" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_INSERTAR_EXAMENES_EXTERNOS" Method="SP_INSERTAR_EXAMENES_EXTERNOS">
    <Parameter Name="CEDULA_PACIENTE" Parameter="cEDULA_PACIENTE" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="APELLIDO_1_PACIENTE" Parameter="aPELLIDO_1_PACIENTE" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="APELLIDO_2_PACIENTE" Parameter="aPELLIDO_2_PACIENTE" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="NOMBRE_PACIENTE" Parameter="nOMBRE_PACIENTE" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="ESPECIALIDAD" Parameter="eSPECIALIDAD" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="FECHA_REGISTRO" Parameter="fECHA_REGISTRO" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="OBSERVACION" Parameter="oBSERVACION" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_BUSCAR_PACIENTE" Method="SP_BUSCAR_PACIENTE">
    <Parameter Name="NOMBRE_PACIENTE" Parameter="nOMBRE_PACIENTE" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="AP1_PACIENTE" Parameter="aP1_PACIENTE" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="AP2_PACIENTE" Parameter="aP2_PACIENTE" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="CED_PACIENTE" Parameter="cED_PACIENTE" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="SP_BUSCAR_PACIENTEResult">
      <Column Name="Nombre" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="Apellido" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="SegundoApellido" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Identificaciòn" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_Selecionar_Paciente" Method="sp_Selecionar_Paciente">
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="sp_Selecionar_PacienteResult">
      <Column Name="NUM_IDENTIFICACION" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="NOM_APELLIDO1" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="NOM_APELLIDO2" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="NOM_NOMBRE" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="IND_SEXO" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="COD_ESTADO_CIVIL" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FEC_NACIMIENTO" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="OBSERVACION" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="NOMBRE_PADRE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="NOMBRE_MADRE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="DOMICILIO" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="CODIGO_PATRONO" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NOMBRE_PATRONO" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="OBSERVACION1" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="BLOQUE_EXPEDIENTE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CUBICULO_EXPEDIENTE" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="FECHA_CREACION_EXPEDIENTE" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="OBSERVACION2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ESTADO_EXPEDIENTE" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="algo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_SELECCIONAR_EXPEDIENTE" Method="SP_SELECCIONAR_EXPEDIENTE">
    <Parameter Name="CEDULA_PACIENTE" Parameter="cEDULA_PACIENTE" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="SP_SELECCIONAR_EXPEDIENTEResult">
      <Column Name="Bloque" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Cubiculo" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Observacion" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GENERAR_HISTORIAL_MOVIMIENTO" Method="GENERAR_HISTORIAL_MOVIMIENTO">
    <Parameter Name="CEDULA_PACIENTE" Parameter="cEDULA_PACIENTE" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="GENERAR_HISTORIAL_MOVIMIENTOResult">
      <Column Name="Área" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Doctor" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Observaciòn" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Estado" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Responsable" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_APLICACIONSEGURIDAD" Method="SP_APLICACIONSEGURIDAD">
    <Parameter Name="USUARIO" Parameter="uSUARIO" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="CLAVE" Parameter="cLAVE" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="SP_APLICACIONSEGURIDADResult">
      <Column Name="EXISTENCIA" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_INSERTAR_MEDICO" Method="SP_INSERTAR_MEDICO">
    <Parameter Name="CODIDO_MEDICO" Parameter="cODIDO_MEDICO" Type="System.Int32" DbType="Int" />
    <Parameter Name="APELLIDO_1_DOCTOR" Parameter="aPELLIDO_1_DOCTOR" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="NOMBRE_DOCTOR" Parameter="nOMBRE_DOCTOR" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="APELLIDO_2_DOCTOR" Parameter="aPELLIDO_2_DOCTOR" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="ESPECIALIDAD" Parameter="eSPECIALIDAD" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="AREA_DE_TRABAJO" Parameter="aREA_DE_TRABAJO" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="EST" Parameter="eST" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_BUSCARDOCTOR" Method="SP_BUSCARDOCTOR">
    <Parameter Name="CODIGO_DOCTOR" Parameter="cODIGO_DOCTOR" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_BUSCARDOCTORResult">
      <Column Name="APELLIDO_1_DOCTOR" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="APELLIDO_2_DOCTOR" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="NOMBRE_DOCTOR" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="ESPECIALIDAD_DOCTOR" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="AREA_TRABAJO_DOCTOR" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="ESTADO_DOCTOR" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="ESTADO" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_ELIMINARDOCTOR" Method="SP_ELIMINARDOCTOR">
    <Parameter Name="CODIGO" Parameter="cODIGO" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_INSERTAR_AREA" Method="SP_INSERTAR_AREA">
    <Parameter Name="AREA_CODIGO" Parameter="aREA_CODIGO" Type="System.Int32" DbType="Int" />
    <Parameter Name="NOMBRE_DEPARTAMENTO" Parameter="nOMBRE_DEPARTAMENTO" Type="System.String" DbType="VarChar(40)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_INSERTAR_USUARIO" Method="SP_INSERTAR_USUARIO">
    <Parameter Name="CEDULA" Parameter="cEDULA" Type="System.Int32" DbType="Int" />
    <Parameter Name="APELLIDO1" Parameter="aPELLIDO1" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="APELLIDO2" Parameter="aPELLIDO2" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="NOMBRE" Parameter="nOMBRE" Type="System.String" DbType="VarChar(25)" />
    <Parameter Name="TELEFONO" Parameter="tELEFONO" Type="System.Int32" DbType="Int" />
    <Parameter Name="CARNET" Parameter="cARNET" Type="System.Int32" DbType="Int" />
    <Parameter Name="DIRECCION" Parameter="dIRECCION" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="FECHA_NACIMIENTO" Parameter="fECHA_NACIMIENTO" Type="System.DateTime" DbType="Date" />
    <Parameter Name="AREA_TRABAJO" Parameter="aREA_TRABAJO" Type="System.String" DbType="VarChar(40)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_SELECCION_USUARIOS" Method="SP_SELECCION_USUARIOS">
    <Parameter Name="CEDULA" Parameter="cEDULA" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_SELECCION_USUARIOSResult">
      <Column Name="APELLIDO_1_FUNCIONARIO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="APELLIDO_2_FUNCIONARIO" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="NOMBRE_FUNCIONARIO" Type="System.String" DbType="VarChar(25)" CanBeNull="true" />
      <Column Name="TELEFONO_FUNCIONARIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CARNET_CCSS_FUNCIONARIO" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="DIRECCION_FUNCIONARIO" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="FECHA_NACIMIENTO" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="AREA_TRABAJO_FUNCIONARIO" Type="System.String" DbType="VarChar(40)" CanBeNull="true" />
      <Column Name="ESTAD" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_INSERTAR_ROLLES" Method="SP_INSERTAR_ROLLES">
    <Parameter Name="CEDULA" Parameter="cEDULA" Type="System.Int32" DbType="Int" />
    <Parameter Name="ROL" Parameter="rOL" Type="System.String" DbType="VarChar(30)" />
    <Parameter Name="CLAVE" Parameter="cLAVE" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
</Database>